## NLP Final
### Part 4: ABSA
### Aren Mizuno
### March 12, 2026

In [61]:
# Imports
!pip -q install pyarrow transformers tqdm

import os
import ast
import re
import numpy as np
import pandas as pd
import torch
import matplotlib.pyplot as plt

from tqdm.auto import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from google.colab import drive
from IPython.display import display
from textwrap import shorten

In [62]:
# Mount drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [92]:
# Paths
NER_PATH = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/parquets/ner.parquet"
BERTOPIC_PATH = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/parquets/bertopic_text.parquet"
MODEL_DIR = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/sentiment_model"

OUTPUT_DIR = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs"

os.makedirs(OUTPUT_DIR, exist_ok=True)

GRAPH_DIR = os.path.join(OUTPUT_DIR, "graphs")
TOPIC_GRAPH_DIR = os.path.join(GRAPH_DIR, "topic_article_sentiment")
COMPANY_GRAPH_DIR = os.path.join(GRAPH_DIR, "topic_top10_companies_sentiment")
TECH_GRAPH_DIR = os.path.join(GRAPH_DIR, "topic_top10_technologies_sentiment")
TIME_GRAPH_DIR = os.path.join(GRAPH_DIR, "topic_sentiment_over_time")

os.makedirs(GRAPH_DIR, exist_ok=True)
os.makedirs(TOPIC_GRAPH_DIR, exist_ok=True)
os.makedirs(COMPANY_GRAPH_DIR, exist_ok=True)
os.makedirs(TECH_GRAPH_DIR, exist_ok=True)
os.makedirs(TIME_GRAPH_DIR, exist_ok=True)

In [66]:
# Load model
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_DIR)

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)
model.eval()

print("Loaded from:", MODEL_DIR)
print("Device:", device)

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

Loaded from: /content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/sentiment_model
Device: cuda

In [67]:
# Load data ner
ner = pd.read_parquet(NER_PATH)
print("ner shape:", ner.shape)
display(ner.head(2))

ner shape: (136233, 8)

,url,date,title,text,text_for_extraction,text_clean,company,technology
0,https://blockworks.co/price/bad,2025-06-23,"Bad Idea AI Price (BAD), Market Cap, Price Tod...","Bad Idea AI Price (BAD), Market Cap, Price Tod...","Bad Idea AI Price (BAD), Market Cap, Price Tod...","bad idea ai price (bad), market cap, price tod...",[Bad Idea AI Price],[]
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,This AI video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,this ai video of gymnastics might be the freak...,"[Instagram, Trump, Werners AI Art]",[]

In [68]:
# Load data bertopic
bertopic_text = pd.read_parquet(BERTOPIC_PATH, engine="pyarrow")
print("bertopic_text shape:", bertopic_text.shape)
display(bertopic_text.head(2))

bertopic_text shape: (136233, 5)

,url,date,title,text,bertopic_topic_text
0,https://blockworks.co/price/bad,2025-06-23,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",bad idea ai price bad market cap price today c...,10
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,This AI video of gymnastics might be the freak...,this ai video of gymnastics might be the freak...,0

In [69]:
# Topic label matching
topic_map = {
    -1: "Cross-Industry AI News / Outliers",
    0: "Enterprise Technology",
    1: "Consumer & Public Services",
    2: "Financial Services & Business",
    3: "Corporate AI Announcements",
    4: "Enterprise Software & Cybersecurity",
    5: "Healthcare & Life Sciences",
    6: "Financial Markets & Investing",
    7: "Media, Journalism & Public Policy",
    8: "Business Operations & Enterprise Automation",
    9: "Workforce & Compensation",
    10: "Cryptocurrency & Digital Assets",
    11: "Publishing & Intellectual Property",
    12: "Public AI Companies",
    13: "Technology Industry News",
    14: "Music & Entertainment",
    15: "African Technology Development",
    16: "AI Market Commentary"
}

In [70]:
# Helper function
def normalize_text(s):
    if s is None:
        return ""
    if isinstance(s, float) and pd.isna(s):
        return ""
    s = str(s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def get_context(text, aspect, window_chars=400, max_total_chars=700):
    """
    If aspect appears in text, grab local context around it.
    Otherwise use the first chunk of the article.
    """
    text = normalize_text(text)
    aspect = normalize_text(aspect)

    if not text:
        return ""

    low_text = text.lower()
    low_aspect = aspect.lower()

    idx = low_text.find(low_aspect)
    if idx == -1:
        return text[:max_total_chars]

    start = max(0, idx - window_chars)
    end = min(len(text), idx + len(aspect) + window_chars)
    snippet = text[start:end]

    if len(snippet) > max_total_chars:
        snippet = snippet[:max_total_chars]

    return snippet

def safe_mode(series):
    vc = series.value_counts(dropna=True)
    return vc.index[0] if len(vc) > 0 else np.nan

def slugify(text, max_len=120):
    text = str(text)
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"\s+", "_", text.strip())
    text = re.sub(r"_+", "_", text)
    if len(text) > max_len:
        text = text[:max_len]
    return text if text else "untitled"

def wrap_or_shorten_labels(labels, max_len=35):
    return [shorten(str(x), width=max_len, placeholder="...") for x in labels]

def ensure_sentiment_columns(pivot_df, sentiments):
    for s in sentiments:
        if s not in pivot_df.columns:
            pivot_df[s] = 0
    return pivot_df[sentiments]

In [71]:
# Keep only needed columns
ner_keep = ["url", "text", "title", "company", "technology", "date"]

bertopic_keep = ["url", "bertopic_topic_text"]

ner_small = ner[ner_keep].copy()
bertopic_small = bertopic_text[bertopic_keep].copy()

ner_small = ner_small.drop_duplicates(subset=["url"])
bertopic_small = bertopic_small.drop_duplicates(subset=["url"])

In [72]:
# Map labels
bertopic_small["bertopic_topic_label"] = bertopic_small["bertopic_topic_text"].map(topic_map)

In [73]:
# Merge on url
df = ner_small.merge(bertopic_small, on="url", how="inner", suffixes=("_ner", "_bertopic"))

print("Merged shape:", df.shape)
display(df.head(2))

Merged shape: (136233, 8)

,url,text,title,company,technology,date,bertopic_topic_text,bertopic_topic_label
0,https://blockworks.co/price/bad,"Bad Idea AI Price (BAD), Market Cap, Price Tod...","Bad Idea AI Price (BAD), Market Cap, Price Tod...",[Bad Idea AI Price],[],2025-06-23,10,Cryptocurrency & Digital Assets
1,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,"[Instagram, Trump, Werners AI Art]",[],2024-07-01,0,Enterprise Technology

In [74]:
# Build aspect row
rows = []

for _, row in tqdm(df.iterrows(), total=len(df), desc="Building aspect rows"):
    url = row["url"]
    title = row["title"]
    full_text = row["text"]
    topic_num = row["bertopic_topic_text"]
    topic_label = row["bertopic_topic_label"]
    date_val = row["date"]

    for aspect in row["company"]:
        context = get_context(full_text, aspect, window_chars=400, max_total_chars=700)
        rows.append({
            "url": url,
            "title": title,
            "date": date_val,
            "bertopic_topic_num": topic_num,
            "bertopic_topic_label": topic_label,
            "aspect_type": "company",
            "aspect": aspect,
            "context": context
        })

    for aspect in row["technology"]:
        context = get_context(full_text, aspect, window_chars=400, max_total_chars=700)
        rows.append({
            "url": url,
            "title": title,
            "date": date_val,
            "bertopic_topic_num": topic_num,
            "bertopic_topic_label": topic_label,
            "aspect_type": "technology",
            "aspect": aspect,
            "context": context
        })

aspect_df = pd.DataFrame(rows)

aspect_df = aspect_df[
    aspect_df["aspect"].astype(str).str.strip().ne("") &
    aspect_df["context"].astype(str).str.strip().ne("")
].copy()

print("Aspect rows shape:", aspect_df.shape)
display(aspect_df.head(10))

# Optional
TOP_N_COMMON = None  # set to int if needed

if TOP_N_COMMON is not None:
    top_aspects = (
        aspect_df.groupby(["aspect_type", "aspect"])
        .size()
        .reset_index(name="mention_count")
        .sort_values(["aspect_type", "mention_count"], ascending=[True, False])
        .groupby("aspect_type", group_keys=False)
        .head(TOP_N_COMMON)
    )

    aspect_df = aspect_df.merge(
        top_aspects[["aspect_type", "aspect"]],
        on=["aspect_type", "aspect"],
        how="inner"
    ).copy()

    print("Aspect rows after top-N filter:", aspect_df.shape)

Building aspect rows:   0%|          | 0/136233 [00:00<?, ?it/s]

Aspect rows shape: (601313, 8)

,url,title,date,bertopic_topic_num,bertopic_topic_label,aspect_type,aspect,context
0,https://blockworks.co/price/bad,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",2025-06-23,10,Cryptocurrency & Digital Assets,company,Bad Idea AI Price,"Bad Idea AI Price (BAD), Market Cap, Price Tod..."
1,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,2024-07-01,0,Enterprise Technology,company,Instagram,hot: Luma AI I'm sure by now you're tired of l...
2,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,2024-07-01,0,Enterprise Technology,company,Trump,s AI video attempt to show gymnastics is one o...
3,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,2024-07-01,0,Enterprise Technology,company,Werners AI Art,"m Mon Jul 1, 2024 Screenshot: Luma AI I'm sure..."
4,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,company,Apple,erfectly functional format of Diskprices. Web ...
5,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,company,Lifetime Subscription,erful Products (Contact Support) Newsletter : ...
6,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,company,Frenchie,et Stand is on sale for just $139.99 (reg. $15...
7,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,technology,ai model,e trying to use it. If you want to make a blog...
8,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,technology,fine-tuning,more jumping from one app to another just to p...
9,https://citylife.capetown/gl/uncategorized/the...,The Road Ahead: How China's AI Foundation Mode...,2023-11-10,0,Enterprise Technology,company,Baidu,"s, China has emerged as a global leader in the..."

In [75]:
# Label mapping
id2label = getattr(model.config, "id2label", None)

if (not id2label) or all(str(v).startswith("LABEL_") for v in id2label.values()):
    id2label = {
        0: "negative",
        1: "neutral",
        2: "positive"
    }

print("Label mapping:", id2label)

label_names_lower = {str(v).lower() for v in id2label.values()}
can_make_score = {"negative", "neutral", "positive"}.issubset(label_names_lower)

Label mapping: {0: 'negative', 1: 'neutral', 2: 'positive'}

In [76]:
# Predict ABSA
def predict_absa(df_in, tokenizer, model, device, batch_size=32, max_length=256):
    all_pred_ids = []
    all_pred_labels = []
    all_probs = []

    contexts = df_in["context"].tolist()
    aspects = df_in["aspect"].tolist()

    for i in tqdm(range(0, len(df_in), batch_size), desc="Running ABSA"):
        batch_contexts = contexts[i:i+batch_size]
        batch_aspects = aspects[i:i+batch_size]

        enc = tokenizer(
            batch_contexts,
            text_pair=batch_aspects,
            padding=True,
            truncation=True,
            max_length=max_length,
            return_tensors="pt"
        )

        enc = {k: v.to(device) for k, v in enc.items()}

        with torch.no_grad():
            outputs = model(**enc)
            probs = torch.softmax(outputs.logits, dim=-1).detach().cpu().numpy()
            pred_ids = probs.argmax(axis=1)

        for pid, pvec in zip(pred_ids, probs):
            all_pred_ids.append(int(pid))
            all_pred_labels.append(str(id2label[int(pid)]).lower())
            all_probs.append(pvec)

    out = df_in.copy()
    out["sentiment_id"] = all_pred_ids
    out["sentiment"] = all_pred_labels

    probs_arr = np.vstack(all_probs)
    for class_id in range(probs_arr.shape[1]):
        label_name = str(id2label[class_id]).lower()
        out[f"prob_{label_name}"] = probs_arr[:, class_id]

    if can_make_score:
        score_map = {"negative": -1, "neutral": 0, "positive": 1}
        out["sentiment_score"] = out["sentiment"].map(score_map)
    else:
        out["sentiment_score"] = np.nan

    return out

absa_df = predict_absa(
    df_in=aspect_df,
    tokenizer=tokenizer,
    model=model,
    device=device,
    batch_size=32,
    max_length=256
)

print("ABSA output shape:", absa_df.shape)
display(absa_df.head(10))

Running ABSA:   0%|          | 0/18792 [00:00<?, ?it/s]

ABSA output shape: (601313, 14)

,url,title,date,bertopic_topic_num,bertopic_topic_label,aspect_type,aspect,context,sentiment_id,sentiment,prob_negative,prob_neutral,prob_positive,sentiment_score
0,https://blockworks.co/price/bad,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",2025-06-23,10,Cryptocurrency & Digital Assets,company,Bad Idea AI Price,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",1,neutral,0.023605,0.973091,0.003304,0
1,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,2024-07-01,0,Enterprise Technology,company,Instagram,hot: Luma AI I'm sure by now you're tired of l...,1,neutral,0.027618,0.960470,0.011913,0
2,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,2024-07-01,0,Enterprise Technology,company,Trump,s AI video attempt to show gymnastics is one o...,1,neutral,0.480598,0.502365,0.017037,0
3,https://boingboing.net/2024/07/01/this-ai-vide...,This AI video of gymnastics might be the freak...,2024-07-01,0,Enterprise Technology,company,Werners AI Art,"m Mon Jul 1, 2024 Screenshot: Luma AI I'm sure...",1,neutral,0.028334,0.961605,0.010062,0
4,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,company,Apple,erfectly functional format of Diskprices. Web ...,1,neutral,0.005597,0.886996,0.107407,0
5,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,company,Lifetime Subscription,erful Products (Contact Support) Newsletter : ...,1,neutral,0.002817,0.989016,0.008166,0
6,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,company,Frenchie,et Stand is on sale for just $139.99 (reg. $15...,1,neutral,0.006160,0.973705,0.020135,0
7,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,technology,ai model,e trying to use it. If you want to make a blog...,1,neutral,0.003533,0.991400,0.005067,0
8,https://boingboing.net/2024/09/18/if-using-ai-...,"If using AI feels like a chore, try this - Boi...",2024-09-22,0,Enterprise Technology,technology,fine-tuning,more jumping from one app to another just to p...,1,neutral,0.002193,0.987968,0.009839,0
9,https://citylife.capetown/gl/uncategorized/the...,The Road Ahead: How China's AI Foundation Mode...,2023-11-10,0,Enterprise Technology,company,Baidu,"s, China has emerged as a global leader in the...",2,positive,0.001893,0.089839,0.908268,1

In [79]:
# Aggregate by aspect (company/technology)
prob_cols = [c for c in absa_df.columns if c.startswith("prob_")]

agg_dict = {
    "url": "nunique",
    "aspect": "size"
}
for c in prob_cols:
    agg_dict[c] = "mean"
if "sentiment_score" in absa_df.columns:
    agg_dict["sentiment_score"] = "mean"

# Main aspect-level aggregate: no topic grouping
aspect_agg_df = (
    absa_df.groupby(["aspect_type", "aspect"])
    .agg(agg_dict)
    .rename(columns={
        "url": "n_unique_articles",
        "aspect": "n_mentions"
    })
    .reset_index()
)

# Dominant sentiment for each aspect
dominant_aspect_sentiment = (
    absa_df.groupby(["aspect_type", "aspect"])["sentiment"]
    .agg(safe_mode)
    .reset_index(name="dominant_sentiment")
)

# Dominant topic for each aspect
dominant_aspect_topic = (
    absa_df.groupby(["aspect_type", "aspect"])["bertopic_topic_label"]
    .agg(safe_mode)
    .reset_index(name="dominant_topic")
)

aspect_agg_df = aspect_agg_df.merge(
    dominant_aspect_sentiment,
    on=["aspect_type", "aspect"],
    how="left"
)

aspect_agg_df = aspect_agg_df.merge(
    dominant_aspect_topic,
    on=["aspect_type", "aspect"],
    how="left"
)

aspect_agg_df = aspect_agg_df.sort_values(
    ["aspect_type", "n_mentions"],
    ascending=[True, False]
).reset_index(drop=True)

# Split into separate company / technology tables
company_aspect_agg_df = (
    aspect_agg_df[aspect_agg_df["aspect_type"] == "company"]
    .copy()
    .reset_index(drop=True)
)

technology_aspect_agg_df = (
    aspect_agg_df[aspect_agg_df["aspect_type"] == "technology"]
    .copy()
    .reset_index(drop=True)
)

print("Aspect aggregate shape:", aspect_agg_df.shape)
display(aspect_agg_df.head(20))

print("\nCompany aspect aggregate shape:", company_aspect_agg_df.shape)
display(company_aspect_agg_df.head(20))

print("\nTechnology aspect aggregate shape:", technology_aspect_agg_df.shape)
display(technology_aspect_agg_df.head(20))

Aspect aggregate shape: (71910, 10)

,aspect_type,aspect,n_unique_articles,n_mentions,prob_negative,prob_neutral,prob_positive,sentiment_score,dominant_sentiment,dominant_topic
0,company,Google,21352,21352,0.139655,0.668384,0.191961,0.028803,neutral,Enterprise Technology
1,company,Microsoft,15467,15467,0.179129,0.590218,0.230654,0.033297,neutral,Enterprise Technology
2,company,Amazon,10361,10361,0.158443,0.587168,0.254390,0.083776,neutral,Enterprise Technology
3,company,Apple,8024,8024,0.171176,0.608252,0.220573,0.030907,neutral,Enterprise Technology
4,company,Instagram,6570,6570,0.143123,0.728548,0.128329,-0.030746,neutral,Enterprise Technology
5,company,Meta,6280,6280,0.194654,0.603368,0.201978,-0.011465,neutral,Enterprise Technology
6,company,Nvidia,5139,5139,0.179948,0.447390,0.372662,0.188947,neutral,Enterprise Technology
7,company,Facebook,4954,4954,0.088585,0.825496,0.085920,-0.009891,neutral,Enterprise Technology
8,company,Nexstar Media Inc,2760,2760,0.096273,0.852398,0.051328,-0.052899,neutral,Consumer & Public Services
9,company,Tesla,2530,2530,0.257936,0.572220,0.169844,-0.109881,neutral,Enterprise Technology
10,company,Samsung,2511,2511,0.105893,0.697186,0.196922,0.072879,neutral,Enterprise Technology
11,company,Intel,2334,2334,0.101822,0.648778,0.249400,0.130677,neutral,Enterprise Technology
12,company,Artificial Intelligence,2249,2249,0.080836,0.753211,0.165953,0.067586,neutral,Enterprise Technology
13,company,Generative AI,2224,2224,0.076223,0.666733,0.257044,0.170863,neutral,Enterprise Technology
14,company,Cision US Inc,2196,2196,0.003175,0.992981,0.003844,0.000000,neutral,Enterprise Software & Cybersecurity
15,company,Newsmatics Inc,2175,2175,0.001755,0.987357,0.010888,0.000000,neutral,Corporate AI Announcements
16,company,Gray Media Group,2151,2151,0.006310,0.879056,0.114634,0.098094,neutral,Business Operations & Enterprise Automation
17,company,"Gray Television, Inc",2118,2118,0.008472,0.987420,0.004108,-0.005194,neutral,Business Operations & Enterprise Automation
18,company,Research,2101,2101,0.006568,0.981454,0.011978,0.005236,neutral,Enterprise Technology
19,company,IBM,2088,2088,0.091381,0.635031,0.273588,0.172893,neutral,Enterprise Technology

Company aspect aggregate shape: (71885, 10)

,aspect_type,aspect,n_unique_articles,n_mentions,prob_negative,prob_neutral,prob_positive,sentiment_score,dominant_sentiment,dominant_topic
0,company,Google,21352,21352,0.139655,0.668384,0.191961,0.028803,neutral,Enterprise Technology
1,company,Microsoft,15467,15467,0.179129,0.590218,0.230654,0.033297,neutral,Enterprise Technology
2,company,Amazon,10361,10361,0.158443,0.587168,0.254390,0.083776,neutral,Enterprise Technology
3,company,Apple,8024,8024,0.171176,0.608252,0.220573,0.030907,neutral,Enterprise Technology
4,company,Instagram,6570,6570,0.143123,0.728548,0.128329,-0.030746,neutral,Enterprise Technology
5,company,Meta,6280,6280,0.194654,0.603368,0.201978,-0.011465,neutral,Enterprise Technology
6,company,Nvidia,5139,5139,0.179948,0.447390,0.372662,0.188947,neutral,Enterprise Technology
7,company,Facebook,4954,4954,0.088585,0.825496,0.085920,-0.009891,neutral,Enterprise Technology
8,company,Nexstar Media Inc,2760,2760,0.096273,0.852398,0.051328,-0.052899,neutral,Consumer & Public Services
9,company,Tesla,2530,2530,0.257936,0.572220,0.169844,-0.109881,neutral,Enterprise Technology
10,company,Samsung,2511,2511,0.105893,0.697186,0.196922,0.072879,neutral,Enterprise Technology
11,company,Intel,2334,2334,0.101822,0.648778,0.249400,0.130677,neutral,Enterprise Technology
12,company,Artificial Intelligence,2249,2249,0.080836,0.753211,0.165953,0.067586,neutral,Enterprise Technology
13,company,Generative AI,2224,2224,0.076223,0.666733,0.257044,0.170863,neutral,Enterprise Technology
14,company,Cision US Inc,2196,2196,0.003175,0.992981,0.003844,0.000000,neutral,Enterprise Software & Cybersecurity
15,company,Newsmatics Inc,2175,2175,0.001755,0.987357,0.010888,0.000000,neutral,Corporate AI Announcements
16,company,Gray Media Group,2151,2151,0.006310,0.879056,0.114634,0.098094,neutral,Business Operations & Enterprise Automation
17,company,"Gray Television, Inc",2118,2118,0.008472,0.987420,0.004108,-0.005194,neutral,Business Operations & Enterprise Automation
18,company,Research,2101,2101,0.006568,0.981454,0.011978,0.005236,neutral,Enterprise Technology
19,company,IBM,2088,2088,0.091381,0.635031,0.273588,0.172893,neutral,Enterprise Technology

Technology aspect aggregate shape: (25, 10)

,aspect_type,aspect,n_unique_articles,n_mentions,prob_negative,prob_neutral,prob_positive,sentiment_score,dominant_sentiment,dominant_topic
0,technology,artificial intelligence,84072,84072,0.117409,0.667934,0.214657,0.082073,neutral,Enterprise Technology
1,technology,generative ai,33503,33503,0.121199,0.600127,0.278674,0.143927,neutral,Enterprise Technology
2,technology,chatbot,27612,27612,0.178968,0.620324,0.200708,0.001449,neutral,Enterprise Technology
3,technology,ai model,24618,24618,0.132768,0.600704,0.266527,0.119669,neutral,Enterprise Technology
4,technology,large language model,20954,20954,0.104917,0.673730,0.221353,0.104085,neutral,Enterprise Technology
5,technology,machine learning,19631,19631,0.059871,0.645415,0.294714,0.232184,neutral,Enterprise Technology
6,technology,robotics,6864,6864,0.050148,0.706923,0.242929,0.187063,neutral,Enterprise Technology
7,technology,deep learning,4369,4369,0.041015,0.648089,0.310896,0.270085,neutral,Enterprise Technology
8,technology,natural language processing,4268,4268,0.032746,0.608284,0.358971,0.323336,neutral,Enterprise Technology
9,technology,computer vision,3314,3314,0.029096,0.669795,0.301109,0.278817,neutral,Enterprise Technology
10,technology,neural network,3149,3149,0.054231,0.690053,0.255717,0.191172,neutral,Enterprise Technology
11,technology,foundation model,2212,2212,0.096120,0.602342,0.301538,0.191682,neutral,Enterprise Technology
12,technology,fine-tuning,1522,1522,0.067301,0.637211,0.295488,0.207622,neutral,Enterprise Technology
13,technology,transformer,1436,1436,0.058295,0.696489,0.245216,0.179666,neutral,Enterprise Technology
14,technology,reinforcement learning,1118,1118,0.052798,0.687876,0.259327,0.194991,neutral,Enterprise Technology
15,technology,retrieval-augmented generation,1062,1062,0.029980,0.744726,0.225293,0.194915,neutral,Enterprise Technology
16,technology,autonomous driving,965,965,0.076578,0.533302,0.390120,0.303627,neutral,Enterprise Technology
17,technology,prompt engineering,923,923,0.049585,0.673176,0.277239,0.239437,neutral,Enterprise Technology
18,technology,multimodal ai,515,515,0.049111,0.593166,0.357723,0.299029,neutral,Enterprise Technology
19,technology,embeddings,284,284,0.027853,0.717195,0.254951,0.204225,neutral,Enterprise Technology

In [80]:
# Aggregate by article
article_agg_dict = {
    "aspect": "size"
}
for c in prob_cols:
    article_agg_dict[c] = "mean"
if "sentiment_score" in absa_df.columns:
    article_agg_dict["sentiment_score"] = "mean"

article_sentiment_df = (
    absa_df.groupby("url")
    .agg(article_agg_dict)
    .rename(columns={"aspect": "n_aspect_mentions"})
    .reset_index()
)

article_dominant_sentiment = (
    absa_df.groupby("url")["sentiment"]
    .agg(safe_mode)
    .reset_index(name="dominant_sentiment")
)

article_dominant_topic = (
    absa_df.groupby("url")["bertopic_topic_label"]
    .agg(safe_mode)
    .reset_index(name="dominant_topic")
)

article_meta = df[["url", "title", "date"]].drop_duplicates(subset=["url"])

article_sentiment_df = article_sentiment_df.merge(article_dominant_sentiment, on="url", how="left")
article_sentiment_df = article_sentiment_df.merge(article_dominant_topic, on="url", how="left")
article_sentiment_df = article_sentiment_df.merge(article_meta, on="url", how="left")

article_sentiment_df = article_sentiment_df.sort_values(
    "n_aspect_mentions",
    ascending=False
).reset_index(drop=True)

print("Article sentiment shape:", article_sentiment_df.shape)
display(article_sentiment_df.head(20))

Article sentiment shape: (134471, 10)

,url,n_aspect_mentions,prob_negative,prob_neutral,prob_positive,sentiment_score,dominant_sentiment,dominant_topic,title,date
0,https://www.techtarget.com/whatis/feature/Arti...,20,0.007558,0.988607,0.003835,0.000000,neutral,Enterprise Technology,Artificial intelligence glossary: 60+ terms to...,2025-08-07
1,https://thenelsonpost.ca/how-research-fuels-ai...,18,0.002007,0.819816,0.178177,0.166667,neutral,Enterprise Technology,How Research Fuels AI Development?,2025-10-17
2,https://venturebeat.com/ai/large-language-mode...,17,0.039188,0.469943,0.490870,0.529412,positive,Enterprise Technology,Large language models broaden AI's reach in in...,2022-12-15
3,https://www.ibm.com/topics/machine-learning-al...,17,0.001882,0.656383,0.341734,0.352941,neutral,Cross-Industry AI News / Outliers,What Is a Machine Learning Algorithm? | IBM,2024-09-02
4,https://www.greenbot.com/ai-systems/,17,0.025968,0.636603,0.337429,0.352941,neutral,Enterprise Technology,"What Is An AI System? Definition, Components &...",2025-02-26
5,https://www.infoworld.com/article/3712283/azur...,17,0.004252,0.973082,0.022666,0.000000,neutral,Enterprise Technology,Azure AI Studio: A nearly complete toolbox for...,2024-01-22
6,https://www.channelasia.tech/article/707067/14...,17,0.005272,0.871249,0.123479,0.117647,neutral,Enterprise Technology,14 popular AI algorithms and their uses - Chan...,2023-05-10
7,https://www.infoworld.com/article/3696970/llms...,16,0.013230,0.948061,0.038709,0.000000,neutral,Enterprise Technology,Large language models and the rise of the AI c...,2023-05-23
8,https://www.ibm.com/think/topics/ai-agent-perc...,16,0.002084,0.600233,0.397683,0.562500,positive,Enterprise Technology,What Is AI Agent Perception? | IBM,2025-03-19
9,https://www.cloudflare.com/en-in/learning/ai/w...,16,0.046371,0.948017,0.005612,-0.062500,neutral,Technology Industry News,What is an LLM (large language model)? | Cloud...,2025-04-24
10,https://menafn.com/1110362940/AI-Strategy-Cour...,16,0.011200,0.529422,0.459378,0.437500,neutral,Enterprise Technology,AI Strategy Courses And Classes Empower Busine...,2025-11-20
11,https://www.ibm.com/think/topics/mistral-ai,15,0.002378,0.815466,0.182157,0.133333,neutral,Cross-Industry AI News / Outliers,What is Mistral AI? | IBM,2024-10-09
12,https://www.ibm.com/think/tutorials/multimodal...,15,0.002402,0.983875,0.013723,0.000000,neutral,Enterprise Technology,Use Llama 3.2-90b-vision-instruct for multimod...,2024-09-30
13,https://www.ibm.com/think/topics/machine-learn...,15,0.001991,0.834422,0.163587,0.133333,neutral,Enterprise Technology,Top Machine Learning Libraries | IBM,2025-08-01
14,https://www.cloudflare.com/en-au/learning/ai/w...,15,0.002398,0.990943,0.006659,0.000000,neutral,Technology Industry News,What is machine learning? | Cloudflare,2025-04-28
15,https://www.geeky-gadgets.com/state-of-ai-repo...,15,0.008097,0.534598,0.457305,0.466667,neutral,Enterprise Technology,2024 State of AI Report: Key Insights and Impl...,2024-10-14
16,https://www.themandarin.com.au/218407-ai-to-z-...,15,0.005265,0.982716,0.012019,0.000000,neutral,Enterprise Technology,AI to Z: All the terms you need to know to kee...,2023-04-26
17,https://blogs.cfainstitute.org/investor/2023/0...,15,0.027867,0.735815,0.236318,0.200000,neutral,Enterprise Technology,ChatGPT and Large Language Models: Six Evoluti...,2023-05-29
18,https://www.ft.com/content/c0c8d205-e158-409e-...,15,0.088476,0.865500,0.046024,-0.066667,neutral,Cross-Industry AI News / Outliers,The FT AI glossary | Financial Times,2023-07-20
19,https://syncedreview.com/2022/01/28/deepmind-p...,15,0.059029,0.606266,0.334705,0.266667,neutral,Enterprise Technology,OpenAI’s InstructGPT Leverages RL From Human F...,2022-01-29

In [81]:
# Aggregate article sentiment by topic
topic_agg_dict = {
    "url": "nunique",
    "n_aspect_mentions": "sum"
}
for c in prob_cols:
    topic_agg_dict[c] = "mean"
if "sentiment_score" in article_sentiment_df.columns:
    topic_agg_dict["sentiment_score"] = "mean"

topic_sentiment_df = (
    article_sentiment_df.groupby("dominant_topic")
    .agg(topic_agg_dict)
    .rename(columns={
        "url": "n_articles",
        "n_aspect_mentions": "total_aspect_mentions"
    })
    .reset_index()
)

topic_dominant_sentiment = (
    article_sentiment_df.groupby("dominant_topic")["dominant_sentiment"]
    .agg(safe_mode)
    .reset_index(name="dominant_topic_sentiment")
)

topic_sentiment_df = topic_sentiment_df.merge(
    topic_dominant_sentiment,
    on="dominant_topic",
    how="left"
)

topic_sentiment_df = topic_sentiment_df.sort_values(
    "n_articles",
    ascending=False
).reset_index(drop=True)

print("Topic sentiment shape:", topic_sentiment_df.shape)
display(topic_sentiment_df.head(18))

Topic sentiment shape: (18, 8)

,dominant_topic,n_articles,total_aspect_mentions,prob_negative,prob_neutral,prob_positive,sentiment_score,dominant_topic_sentiment
0,Enterprise Technology,60488,272266,0.114487,0.669307,0.216206,0.087240,neutral
1,Cross-Industry AI News / Outliers,35451,157728,0.116044,0.704343,0.179613,0.048681,neutral
2,Consumer & Public Services,6337,30213,0.164874,0.717683,0.117443,-0.066746,neutral
3,Financial Services & Business,5514,23934,0.136029,0.658085,0.205886,0.056795,neutral
4,Corporate AI Announcements,3572,16615,0.018250,0.677359,0.304392,0.282327,neutral
5,Enterprise Software & Cybersecurity,3270,16406,0.011442,0.758684,0.229874,0.215169,neutral
6,Healthcare & Life Sciences,3041,13155,0.056361,0.682187,0.261452,0.199861,neutral
7,Financial Markets & Investing,2808,14211,0.115787,0.568664,0.315548,0.197858,neutral
8,"Media, Journalism & Public Policy",2769,11636,0.134043,0.809334,0.056623,-0.087225,neutral
9,Business Operations & Enterprise Automation,1948,9154,0.014840,0.713867,0.271293,0.256488,neutral
10,Workforce & Compensation,1513,4480,0.003913,0.986333,0.009754,0.002082,neutral
11,Cryptocurrency & Digital Assets,1246,3183,0.083056,0.774138,0.142806,0.039139,neutral
12,Publishing & Intellectual Property,1199,5699,0.179448,0.689052,0.131500,-0.069111,neutral
13,Public AI Companies,1177,4391,0.135616,0.557479,0.306904,0.174081,neutral
14,Technology Industry News,1109,5432,0.207200,0.431575,0.361225,0.140909,neutral
15,Music & Entertainment,1028,3858,0.148395,0.761588,0.090017,-0.082988,neutral
16,African Technology Development,1012,4564,0.115033,0.648157,0.236811,0.105990,neutral
17,AI Market Commentary,989,4388,0.090800,0.500163,0.409037,0.325183,neutral

In [83]:
# Top companies by topic
TOP_K = 20

company_by_topic = (
    absa_df[absa_df["aspect_type"] == "company"]
    .groupby(["bertopic_topic_label", "aspect"])
    .agg(
        n_mentions=("aspect", "size"),
        n_unique_articles=("url", "nunique"),
        prob_negative=("prob_negative", "mean"),
        prob_neutral=("prob_neutral", "mean"),
        prob_positive=("prob_positive", "mean"),
        dominant_sentiment=("sentiment", safe_mode)
    )
    .reset_index()
)

# Sort so top mentions appear first inside each topic
company_by_topic = company_by_topic.sort_values(
    ["bertopic_topic_label", "n_mentions"],
    ascending=[True, False]
)

# Dictionary of dataframes: {topic: dataframe}
company_topic_dfs = {
    topic: df.head(TOP_K).reset_index(drop=True)
    for topic, df in company_by_topic.groupby("bertopic_topic_label")
}

# Example: display them
for topic, df_topic in company_topic_dfs.items():
    print(f"\nTopic: {topic}")
    display(df_topic)

Topic: AI Market Commentary

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,AI Market Commentary,My European Quotes,446,446,0.002957,0.991913,0.005130,neutral
1,AI Market Commentary,Motley,269,269,0.142973,0.358172,0.498855,positive
2,AI Market Commentary,Nvidia,261,261,0.105362,0.326768,0.567870,positive
3,AI Market Commentary,Amazon,170,170,0.138835,0.322596,0.538569,positive
4,AI Market Commentary,Microsoft,134,134,0.098655,0.325871,0.575474,positive
5,AI Market Commentary,Alphabet,122,122,0.076321,0.358496,0.565183,positive
6,AI Market Commentary,TradeTalks,116,116,0.002839,0.984264,0.012898,neutral
7,AI Market Commentary,AMD,63,63,0.568562,0.347268,0.084170,negative
8,AI Market Commentary,"Nasdaq, Inc",61,61,0.008065,0.923836,0.068099,neutral
9,AI Market Commentary,Google,60,60,0.149676,0.397481,0.452843,positive
10,AI Market Commentary,Apple,58,58,0.209415,0.388730,0.401855,positive
11,AI Market Commentary,Intel,51,51,0.016825,0.876511,0.106664,neutral
12,AI Market Commentary,Watchlist,43,43,0.002827,0.991179,0.005994,neutral
13,AI Market Commentary,"Nasdaq, Inc. Tags",41,41,0.051271,0.926599,0.022130,neutral
14,AI Market Commentary,Meta,33,33,0.582535,0.323204,0.094261,negative
15,AI Market Commentary,"Nasdaq, Inc. All",31,31,0.006938,0.990240,0.002822,neutral
16,AI Market Commentary,Oracle,26,26,0.117047,0.286246,0.596707,positive
17,AI Market Commentary,Broadcom,24,24,0.010675,0.518153,0.471172,neutral
18,AI Market Commentary,Instagram,23,23,0.056969,0.365025,0.578005,positive
19,AI Market Commentary,Tesla,18,18,0.110333,0.372261,0.517407,positive

Topic: African Technology Development

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,African Technology Development,Google,176,176,0.089688,0.636120,0.274191,neutral
1,African Technology Development,Arena Holdings,114,114,0.250938,0.586134,0.162927,neutral
2,African Technology Development,Microsoft,98,98,0.230138,0.549366,0.220496,neutral
3,African Technology Development,Facebook,62,62,0.177986,0.612301,0.209713,neutral
4,African Technology Development,Apple,52,52,0.233739,0.569693,0.196568,neutral
5,African Technology Development,Twitter,43,43,0.003685,0.971491,0.024824,neutral
6,African Technology Development,Meta,41,41,0.239212,0.504206,0.256582,neutral
7,African Technology Development,Instagram,40,40,0.145825,0.620719,0.233456,neutral
8,African Technology Development,Amazon,39,39,0.204178,0.518745,0.277076,neutral
9,African Technology Development,Artificial Intelligence,38,38,0.061675,0.741466,0.196859,neutral
10,African Technology Development,Nvidia,36,36,0.214252,0.457668,0.328080,neutral
11,African Technology Development,THISDAY NEWSPAPERS LTD,31,31,0.011244,0.729748,0.259008,neutral
12,African Technology Development,DIGGER MOTORS,27,27,0.002894,0.991881,0.005226,neutral
13,African Technology Development,Huawei,23,23,0.108253,0.581646,0.310101,neutral
14,African Technology Development,Innovation,23,23,0.005887,0.725962,0.268151,neutral
15,African Technology Development,Artificial Intelligence (AI,22,22,0.018889,0.846577,0.134533,neutral
16,African Technology Development,GDPR Cookie Consent,21,21,0.023510,0.968251,0.008239,neutral
17,African Technology Development,Alphabet,18,18,0.213512,0.397300,0.389188,neutral
18,African Technology Development,Education,17,17,0.050852,0.862754,0.086394,neutral
19,African Technology Development,HapaKenya Media Ltd,17,17,0.002557,0.652758,0.344685,neutral

Topic: Business Operations & Enterprise Automation

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Business Operations & Enterprise Automation,Gray Media Group,1436,1436,0.005328,0.878923,0.115749,neutral
1,Business Operations & Enterprise Automation,"Gray Television, Inc",1385,1385,0.004379,0.991903,0.003718,neutral
2,Business Operations & Enterprise Automation,"Gray Media Group, Inc",335,335,0.005894,0.938789,0.055318,neutral
3,Business Operations & Enterprise Automation,PRNewswire,316,316,0.009893,0.511312,0.478795,neutral
4,Business Operations & Enterprise Automation,Google,83,83,0.034437,0.625863,0.339700,neutral
5,Business Operations & Enterprise Automation,Generative AI,74,74,0.032513,0.649463,0.318024,neutral
6,Business Operations & Enterprise Automation,Amazon,55,55,0.015349,0.660933,0.323718,neutral
7,Business Operations & Enterprise Automation,Artificial Intelligence,48,48,0.025978,0.687506,0.286515,neutral
8,Business Operations & Enterprise Automation,Microsoft,46,46,0.041922,0.587744,0.370334,neutral
9,Business Operations & Enterprise Automation,Instagram,39,39,0.005763,0.725554,0.268682,neutral
10,Business Operations & Enterprise Automation,CareersGray Media Group,30,30,0.003005,0.987981,0.009014,neutral
11,Business Operations & Enterprise Automation,Apple,25,25,0.081149,0.733241,0.185611,neutral
12,Business Operations & Enterprise Automation,Intel,24,24,0.003109,0.745352,0.251539,neutral
13,Business Operations & Enterprise Automation,CNW Group,20,20,0.002489,0.719371,0.278140,neutral
14,Business Operations & Enterprise Automation,Digital,20,20,0.080121,0.539199,0.380681,neutral
15,Business Operations & Enterprise Automation,Graham Holdings,20,20,0.002978,0.949549,0.047473,neutral
16,Business Operations & Enterprise Automation,Meta,20,20,0.009065,0.697744,0.293191,neutral
17,Business Operations & Enterprise Automation,"LZG International, Inc",19,19,0.002370,0.373849,0.623781,positive
18,Business Operations & Enterprise Automation,Apple Awards,17,17,0.002541,0.992629,0.004831,neutral
19,Business Operations & Enterprise Automation,Graham Media Group,17,17,0.003822,0.964623,0.031555,neutral

Topic: Consumer & Public Services

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Consumer & Public Services,Nexstar Media Inc,1863,1863,0.089122,0.861864,0.049014,neutral
1,Consumer & Public Services,Google,1564,1564,0.180449,0.646812,0.172739,neutral
2,Consumer & Public Services,Microsoft,1083,1083,0.257552,0.594414,0.148034,neutral
3,Consumer & Public Services,BestReviews,795,795,0.052922,0.871008,0.076070,neutral
4,Consumer & Public Services,Amazon,765,765,0.160764,0.652927,0.186309,neutral
5,Consumer & Public Services,Facebook,471,471,0.103209,0.853361,0.043431,neutral
6,Consumer & Public Services,Meta,399,399,0.241584,0.580681,0.177735,neutral
7,Consumer & Public Services,Apple,365,365,0.152168,0.679227,0.168605,neutral
8,Consumer & Public Services,Instagram,289,289,0.296525,0.649324,0.054151,neutral
9,Consumer & Public Services,Android,210,210,0.139344,0.798090,0.062566,neutral
10,Consumer & Public Services,Tesla,182,182,0.241469,0.712413,0.046118,neutral
11,Consumer & Public Services,Altman,178,178,0.272164,0.679570,0.048266,neutral
12,Consumer & Public Services,Commonwealth,154,154,0.002543,0.993879,0.003579,neutral
13,Consumer & Public Services,Congress,147,147,0.115816,0.828627,0.055556,neutral
14,Consumer & Public Services,"Idaho, Inc",146,146,0.003630,0.992497,0.003873,neutral
15,Consumer & Public Services,Palm Springs,145,145,0.019316,0.732921,0.247763,neutral
16,Consumer & Public Services,AP Photo,128,128,0.161980,0.797652,0.040368,neutral
17,Consumer & Public Services,Baidu,97,97,0.193032,0.704796,0.102172,neutral
18,Consumer & Public Services,"Scripps Media, Inc",95,95,0.106855,0.708256,0.184888,neutral
19,Consumer & Public Services,The Associated Press,95,95,0.173567,0.700089,0.126344,neutral

Topic: Corporate AI Announcements

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Corporate AI Announcements,Newsmatics Inc,2102,2102,0.001755,0.987375,0.010869,neutral
1,Corporate AI Announcements,Industry Newswires,1142,1142,0.011424,0.807065,0.181511,neutral
2,Corporate AI Announcements,EIN Presswire,446,446,0.013080,0.704969,0.281951,neutral
3,Corporate AI Announcements,Google,205,205,0.063716,0.614099,0.322185,neutral
4,Corporate AI Announcements,New Mexico,203,203,0.008582,0.983081,0.008336,neutral
5,Corporate AI Announcements,Microsoft,122,122,0.041985,0.496459,0.461556,neutral
6,Corporate AI Announcements,Allied Analytics LLP,114,114,0.004464,0.478905,0.516631,positive
7,Corporate AI Announcements,TBRC Research Pvt Ltd,114,114,0.002960,0.660274,0.336766,neutral
8,Corporate AI Announcements,IBM,103,103,0.020779,0.499034,0.480187,positive
9,Corporate AI Announcements,Generative AI,98,98,0.008642,0.592305,0.399053,neutral
10,Corporate AI Announcements,Amazon,93,93,0.028429,0.603361,0.368210,neutral
11,Corporate AI Announcements,Allied Market Research,71,71,0.002823,0.579986,0.417191,neutral
12,Corporate AI Announcements,Artificial Intelligence,67,67,0.030017,0.710218,0.259764,neutral
13,Corporate AI Announcements,Instagram,49,49,0.020232,0.622621,0.357146,neutral
14,Corporate AI Announcements,Agentic AI,42,42,0.017306,0.597801,0.384893,neutral
15,Corporate AI Announcements,Facebook,40,40,0.068838,0.735913,0.195249,neutral
16,Corporate AI Announcements,Intel,38,38,0.004342,0.507268,0.488390,neutral
17,Corporate AI Announcements,Apple,36,36,0.036731,0.505282,0.457987,neutral
18,Corporate AI Announcements,Healthcare,34,34,0.002186,0.988031,0.009782,neutral
19,Corporate AI Announcements,"IPD Group, Inc",34,34,0.002023,0.988777,0.009200,neutral

Topic: Cross-Industry AI News / Outliers

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Cross-Industry AI News / Outliers,Google,5095,5095,0.156808,0.665863,0.177330,neutral
1,Cross-Industry AI News / Outliers,Microsoft,3919,3919,0.192454,0.594408,0.213138,neutral
2,Cross-Industry AI News / Outliers,Amazon,2681,2681,0.174208,0.596865,0.228928,neutral
3,Cross-Industry AI News / Outliers,Instagram,2123,2123,0.132889,0.767281,0.099830,neutral
4,Cross-Industry AI News / Outliers,Apple,2119,2119,0.174746,0.625011,0.200243,neutral
5,Cross-Industry AI News / Outliers,Facebook,1744,1744,0.073281,0.872293,0.054426,neutral
6,Cross-Industry AI News / Outliers,Meta,1573,1573,0.205038,0.602487,0.192474,neutral
7,Cross-Industry AI News / Outliers,Nvidia,1309,1309,0.195419,0.462526,0.342055,neutral
8,Cross-Industry AI News / Outliers,Digital,897,897,0.046920,0.777946,0.175134,neutral
9,Cross-Industry AI News / Outliers,Nexstar Media Inc,777,777,0.106921,0.839023,0.054055,neutral
10,Cross-Industry AI News / Outliers,Tesla,717,717,0.274375,0.555073,0.170552,neutral
11,Cross-Industry AI News / Outliers,Trump,644,644,0.269797,0.617714,0.112489,neutral
12,Cross-Industry AI News / Outliers,Artificial Intelligence,591,591,0.084496,0.766314,0.149190,neutral
13,Cross-Industry AI News / Outliers,Intel,531,531,0.097740,0.660115,0.242146,neutral
14,Cross-Industry AI News / Outliers,Twitter,500,500,0.173564,0.771933,0.054502,neutral
15,Cross-Industry AI News / Outliers,Alphabet,494,494,0.265376,0.428257,0.306367,neutral
16,Cross-Industry AI News / Outliers,Samsung,480,480,0.112258,0.686911,0.200831,neutral
17,Cross-Industry AI News / Outliers,Generative AI,470,470,0.099663,0.638994,0.261343,neutral
18,Cross-Industry AI News / Outliers,IBM,466,466,0.089483,0.662557,0.247959,neutral
19,Cross-Industry AI News / Outliers,AMD,453,453,0.154738,0.502531,0.342731,neutral

Topic: Cryptocurrency & Digital Assets

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Cryptocurrency & Digital Assets,Ethereum,214,214,0.060093,0.899361,0.040547,neutral
1,Cryptocurrency & Digital Assets,Bollinger Bands,210,210,0.005718,0.929833,0.064449,neutral
2,Cryptocurrency & Digital Assets,Google,195,195,0.155666,0.587094,0.257239,neutral
3,Cryptocurrency & Digital Assets,Bitcoin,75,75,0.278809,0.536033,0.185158,neutral
4,Cryptocurrency & Digital Assets,AITECH,60,60,0.144542,0.733155,0.122303,neutral
5,Cryptocurrency & Digital Assets,Account,56,56,0.073432,0.848680,0.077889,neutral
6,Cryptocurrency & Digital Assets,DepositStep,44,44,0.001110,0.982783,0.016107,neutral
7,Cryptocurrency & Digital Assets,Link Machine Learning,37,37,0.075116,0.805000,0.119884,neutral
8,Cryptocurrency & Digital Assets,MEXC Spot,33,33,0.001972,0.964513,0.033516,neutral
9,Cryptocurrency & Digital Assets,Daily Email,27,27,0.107849,0.777973,0.114178,neutral
10,Cryptocurrency & Digital Assets,STETH,23,23,0.290394,0.346653,0.362953,positive
11,Cryptocurrency & Digital Assets,NASDAQ,22,22,0.303578,0.390825,0.305598,neutral
12,Cryptocurrency & Digital Assets,UpdatesBitcoin,18,18,0.009149,0.041471,0.949380,positive
13,Cryptocurrency & Digital Assets,LLC Sells,16,16,0.124873,0.581263,0.293864,neutral
14,Cryptocurrency & Digital Assets,ArbDoge AI,14,14,0.076188,0.754790,0.169022,neutral
15,Cryptocurrency & Digital Assets,"Cisco Systems, Inc",14,14,0.294497,0.385821,0.319682,positive
16,Cryptocurrency & Digital Assets,NYSEARCA,14,14,0.257979,0.393902,0.348119,neutral
17,Cryptocurrency & Digital Assets,Decentralized Machine Learning,12,12,0.081982,0.896257,0.021761,neutral
18,Cryptocurrency & Digital Assets,Multi-Product,11,11,0.002751,0.469861,0.527388,positive
19,Cryptocurrency & Digital Assets,"Applied Materials, Inc",10,10,0.102022,0.604162,0.293817,neutral

Topic: Enterprise Software & Cybersecurity

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Enterprise Software & Cybersecurity,Cision US Inc,2062,2062,0.003120,0.993096,0.003784,neutral
1,Enterprise Software & Cybersecurity,PR Newswire,631,631,0.003965,0.954876,0.041159,neutral
2,Enterprise Software & Cybersecurity,Release Resources Journalists,364,364,0.008279,0.825834,0.165887,neutral
3,Enterprise Software & Cybersecurity,CNW Group Ltd,289,289,0.002993,0.993731,0.003276,neutral
4,Enterprise Software & Cybersecurity,Call PR Newswire,192,192,0.016751,0.669205,0.314044,neutral
5,Enterprise Software & Cybersecurity,Client Send,192,192,0.014094,0.767304,0.218602,neutral
6,Enterprise Software & Cybersecurity,Register Now,183,183,0.003464,0.634982,0.361554,neutral
7,Enterprise Software & Cybersecurity,Google,111,111,0.005614,0.573102,0.421284,neutral
8,Enterprise Software & Cybersecurity,Microsoft,111,111,0.022285,0.546000,0.431715,neutral
9,Enterprise Software & Cybersecurity,Generative AI,110,110,0.012191,0.601304,0.386505,neutral
10,Enterprise Software & Cybersecurity,Amazon,89,89,0.008265,0.659599,0.332136,neutral
11,Enterprise Software & Cybersecurity,Artificial Intelligence,73,73,0.002028,0.884193,0.113778,neutral
12,Enterprise Software & Cybersecurity,CRN INDIA Technology,69,69,0.006282,0.869600,0.124118,neutral
13,Enterprise Software & Cybersecurity,Instagram,61,61,0.004895,0.714602,0.280503,neutral
14,Enterprise Software & Cybersecurity,Meta,58,58,0.002111,0.939435,0.058454,neutral
15,Enterprise Software & Cybersecurity,Intel,56,56,0.002322,0.946010,0.051668,neutral
16,Enterprise Software & Cybersecurity,IBM,51,51,0.021217,0.627745,0.351038,neutral
17,Enterprise Software & Cybersecurity,CRN INDIA,48,48,0.003005,0.992437,0.004558,neutral
18,Enterprise Software & Cybersecurity,Agentic AI,41,41,0.029859,0.597318,0.372824,neutral
19,Enterprise Software & Cybersecurity,Apple,38,38,0.031976,0.536783,0.431242,neutral

Topic: Enterprise Technology

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Enterprise Technology,Google,10187,10187,0.134193,0.665457,0.200350,neutral
1,Enterprise Technology,Microsoft,7951,7951,0.163813,0.608849,0.227338,neutral
2,Enterprise Technology,Amazon,4973,4973,0.148202,0.604162,0.247636,neutral
3,Enterprise Technology,Apple,4303,4303,0.170461,0.608579,0.220960,neutral
4,Enterprise Technology,Meta,3283,3283,0.179187,0.608553,0.212260,neutral
5,Enterprise Technology,Instagram,3090,3090,0.130418,0.725820,0.143761,neutral
6,Enterprise Technology,Nvidia,2572,2572,0.190410,0.467557,0.342033,neutral
7,Enterprise Technology,Facebook,2039,2039,0.100662,0.783622,0.115717,neutral
8,Enterprise Technology,Samsung,1764,1764,0.097228,0.719911,0.182861,neutral
9,Enterprise Technology,Research,1630,1630,0.006507,0.982730,0.010763,neutral
10,Enterprise Technology,Intel,1324,1324,0.101108,0.637791,0.261101,neutral
11,Enterprise Technology,Tesla,1221,1221,0.253507,0.577209,0.169284,neutral
12,Enterprise Technology,Generative AI,1210,1210,0.062221,0.704645,0.233134,neutral
13,Enterprise Technology,Future US Inc,1201,1201,0.112198,0.726443,0.161360,neutral
14,Enterprise Technology,Artificial Intelligence,1144,1144,0.080082,0.750329,0.169589,neutral
15,Enterprise Technology,IBM,1137,1137,0.096440,0.631761,0.271799,neutral
16,Enterprise Technology,AMD,1105,1105,0.120675,0.577657,0.301668,neutral
17,Enterprise Technology,Altman,927,927,0.250878,0.645930,0.103192,neutral
18,Enterprise Technology,Trump,887,887,0.290511,0.548080,0.161409,neutral
19,Enterprise Technology,Market Data,874,874,0.034019,0.812876,0.153105,neutral

Topic: Financial Markets & Investing

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Financial Markets & Investing,"Nasdaq, Inc. All",631,631,0.002983,0.985495,0.011522,neutral
1,Financial Markets & Investing,Microsoft,511,511,0.149573,0.456550,0.393877,neutral
2,Financial Markets & Investing,Amazon,452,452,0.154215,0.409283,0.436503,positive
3,Financial Markets & Investing,Google,434,434,0.158778,0.556515,0.284707,neutral
4,Financial Markets & Investing,Nvidia,404,404,0.120106,0.376883,0.503012,positive
5,Financial Markets & Investing,Indian Railway Corporation,337,337,0.088053,0.822747,0.089200,neutral
6,Financial Markets & Investing,Apple,288,288,0.165733,0.458731,0.375536,neutral
7,Financial Markets & Investing,Alphabet,249,249,0.164837,0.405569,0.429594,positive
8,Financial Markets & Investing,Watchlist,183,183,0.002700,0.988162,0.009138,neutral
9,Financial Markets & Investing,TSLA AAPL,147,147,0.003543,0.993894,0.002562,neutral
10,Financial Markets & Investing,Tesla,133,133,0.261395,0.425877,0.312727,neutral
11,Financial Markets & Investing,AMD,131,131,0.294054,0.354417,0.351530,positive
12,Financial Markets & Investing,Motley,128,128,0.101548,0.468741,0.429711,positive
13,Financial Markets & Investing,Meta,123,123,0.180924,0.522379,0.296698,neutral
14,Financial Markets & Investing,Intel,118,118,0.105821,0.700348,0.193831,neutral
15,Financial Markets & Investing,Instagram,106,106,0.125801,0.597430,0.276769,neutral
16,Financial Markets & Investing,Alphabet Inc,80,80,0.147881,0.473065,0.379054,neutral
17,Financial Markets & Investing,AXIS BANK,63,63,0.002638,0.960358,0.037004,neutral
18,Financial Markets & Investing,THG PUBLISHING PVT LTD,61,61,0.116274,0.849210,0.034515,neutral
19,Financial Markets & Investing,IBM,55,55,0.139798,0.524716,0.335486,neutral

Topic: Financial Services & Business

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Financial Services & Business,Google,784,784,0.163809,0.622014,0.214178,neutral
1,Financial Services & Business,Microsoft,633,633,0.175398,0.546153,0.278449,neutral
2,Financial Services & Business,Standard Private Ltd,445,445,0.005728,0.988126,0.006146,neutral
3,Financial Services & Business,Amazon,428,428,0.194187,0.539717,0.266096,neutral
4,Financial Services & Business,Apple,342,342,0.189640,0.593196,0.217163,neutral
5,Financial Services & Business,Instagram,315,315,0.211963,0.664307,0.123730,neutral
6,Financial Services & Business,Meta,288,288,0.214702,0.565059,0.220240,neutral
7,Financial Services & Business,ChartsForex,280,280,0.006395,0.986789,0.006816,neutral
8,Financial Services & Business,Nvidia,246,246,0.181039,0.439445,0.379516,neutral
9,Financial Services & Business,Technologies,151,151,0.019306,0.911656,0.069038,neutral
10,Financial Services & Business,StocksTop,142,142,0.022891,0.926877,0.050232,neutral
11,Financial Services & Business,HandleFlags,137,137,0.004159,0.990576,0.005265,neutral
12,Financial Services & Business,Tesla,134,134,0.237179,0.599399,0.163422,neutral
13,Financial Services & Business,Malayalam,131,131,0.159046,0.763878,0.077076,neutral
14,Financial Services & Business,Facebook,118,118,0.095510,0.794792,0.109698,neutral
15,Financial Services & Business,Trump,97,97,0.240859,0.653554,0.105588,neutral
16,Financial Services & Business,AMD,96,96,0.165896,0.484246,0.349858,neutral
17,Financial Services & Business,Alphabet Inc,95,95,0.160513,0.488510,0.350977,neutral
18,Financial Services & Business,Alphabet,91,91,0.246668,0.428433,0.324899,neutral
19,Financial Services & Business,Advertisers,90,90,0.002078,0.993925,0.003996,neutral

Topic: Healthcare & Life Sciences

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Healthcare & Life Sciences,Google,223,223,0.132399,0.641349,0.226252,neutral
1,Healthcare & Life Sciences,Research,140,140,0.008463,0.967669,0.023868,neutral
2,Healthcare & Life Sciences,Microsoft,125,125,0.083582,0.661324,0.255094,neutral
3,Healthcare & Life Sciences,Healthcare,122,122,0.034045,0.670039,0.295916,neutral
4,Healthcare & Life Sciences,Amazon,104,104,0.113666,0.573429,0.312906,neutral
5,Healthcare & Life Sciences,Facebook,103,103,0.051896,0.792767,0.155337,neutral
6,Healthcare & Life Sciences,Artificial Intelligence,80,80,0.037072,0.763746,0.199182,neutral
7,Healthcare & Life Sciences,Instagram,80,80,0.143645,0.768899,0.087456,neutral
8,Healthcare & Life Sciences,Market Data,79,79,0.015185,0.839966,0.144849,neutral
9,Healthcare & Life Sciences,Apple,76,76,0.167594,0.618857,0.213550,neutral
10,Healthcare & Life Sciences,"Gray Television, Inc",56,56,0.002642,0.992722,0.004636,neutral
11,Healthcare & Life Sciences,IBM,53,53,0.066935,0.723100,0.209966,neutral
12,Healthcare & Life Sciences,BioSpace,52,52,0.005747,0.661511,0.332741,neutral
13,Healthcare & Life Sciences,Gray Media Group,42,42,0.010559,0.807487,0.181954,neutral
14,Healthcare & Life Sciences,Digital,38,38,0.036146,0.713520,0.250335,neutral
15,Healthcare & Life Sciences,Generative AI,33,33,0.043175,0.680087,0.276738,neutral
16,Healthcare & Life Sciences,Internet Marketing Company,32,32,0.001737,0.973044,0.025218,neutral
17,Healthcare & Life Sciences,Trump,32,32,0.220322,0.601377,0.178301,neutral
18,Healthcare & Life Sciences,ScienceDaily,29,29,0.050345,0.916824,0.032832,neutral
19,Healthcare & Life Sciences,Meta,28,28,0.190546,0.658212,0.151242,neutral

Topic: Media, Journalism & Public Policy

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,"Media, Journalism & Public Policy",Google,360,360,0.184490,0.686313,0.129196,neutral
1,"Media, Journalism & Public Policy",Microsoft,296,296,0.287631,0.616889,0.095480,neutral
2,"Media, Journalism & Public Policy",Meta,204,204,0.253496,0.668164,0.078340,neutral
3,"Media, Journalism & Public Policy",Community Advisory Board,178,178,0.002228,0.986737,0.011035,neutral
4,"Media, Journalism & Public Policy",Facebook,165,165,0.093252,0.863670,0.043078,neutral
5,"Media, Journalism & Public Policy",Amazon,150,150,0.195679,0.693702,0.110619,neutral
6,"Media, Journalism & Public Policy",Instagram,148,148,0.180921,0.757333,0.061745,neutral
7,"Media, Journalism & Public Policy",Apple,105,105,0.264144,0.702860,0.032995,neutral
8,"Media, Journalism & Public Policy",Digital TV Channels,102,102,0.004223,0.989500,0.006277,neutral
9,"Media, Journalism & Public Policy",Trump,98,98,0.262373,0.672532,0.065094,neutral
10,"Media, Journalism & Public Policy",Congress,89,89,0.206816,0.772843,0.020341,neutral
11,"Media, Journalism & Public Policy",Programs Access,74,74,0.049342,0.936242,0.014416,neutral
12,"Media, Journalism & Public Policy",Deepa Shivaram,64,64,0.013727,0.955827,0.030446,neutral
13,"Media, Journalism & Public Policy",NewsDepth PBS,61,61,0.004220,0.991601,0.004179,neutral
14,"Media, Journalism & Public Policy",FCC Public Inspection,60,60,0.002702,0.989267,0.008031,neutral
15,"Media, Journalism & Public Policy",FAQ & Resources,53,53,0.002000,0.979183,0.018817,neutral
16,"Media, Journalism & Public Policy",Facebook Twitter,53,53,0.054625,0.854465,0.090910,neutral
17,"Media, Journalism & Public Policy",Main Program,49,49,0.003712,0.992495,0.003793,neutral
18,"Media, Journalism & Public Policy",Aspen Public Radio,46,46,0.179130,0.790807,0.030063,neutral
19,"Media, Journalism & Public Policy",Committees Jobs Internships,45,45,0.002883,0.993524,0.003593,neutral

Topic: Music & Entertainment

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Music & Entertainment,Google,116,116,0.144981,0.756761,0.098258,neutral
1,Music & Entertainment,Instagram,100,100,0.228862,0.705245,0.065893,neutral
2,Music & Entertainment,Apple,67,67,0.113998,0.730826,0.155175,neutral
3,Music & Entertainment,Universal Music Group,63,63,0.330157,0.514555,0.155288,neutral
4,Music & Entertainment,Facebook,62,62,0.036367,0.918955,0.044677,neutral
5,Music & Entertainment,Spotify,61,61,0.156169,0.712843,0.130988,neutral
6,Music & Entertainment,Amazon,56,56,0.213203,0.656998,0.129799,neutral
7,Music & Entertainment,Microsoft,48,48,0.236701,0.631467,0.131832,neutral
8,Music & Entertainment,Meta,33,33,0.153300,0.617090,0.229610,neutral
9,Music & Entertainment,Twitter,31,31,0.081145,0.881797,0.037057,neutral
10,Music & Entertainment,Altman,30,30,0.717945,0.272563,0.009492,negative
11,Music & Entertainment,YouTube,25,25,0.159547,0.816051,0.024402,neutral
12,Music & Entertainment,Artificial Intelligence,21,21,0.301407,0.645979,0.052614,neutral
13,Music & Entertainment,Samsung,21,21,0.116805,0.802936,0.080259,neutral
14,Music & Entertainment,National Publishing Ltd,19,19,0.085207,0.895411,0.019382,neutral
15,Music & Entertainment,Research,19,19,0.003719,0.992848,0.003433,neutral
16,Music & Entertainment,Trump,19,19,0.311880,0.659441,0.028680,neutral
17,Music & Entertainment,Cox Media Group,16,16,0.002193,0.986389,0.011418,neutral
18,Music & Entertainment,Deezer,15,15,0.183822,0.717433,0.098746,neutral
19,Music & Entertainment,Facebook Instagram TikTok,14,14,0.378924,0.542445,0.078631,neutral

Topic: Public AI Companies

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Public AI Companies,Google,161,161,0.153848,0.609027,0.237125,neutral
1,Public AI Companies,NASDAQ,54,54,0.183120,0.547490,0.269390,neutral
2,Public AI Companies,Palladyne AI Corp,39,39,0.038253,0.377190,0.584556,positive
3,Public AI Companies,SES AI Corporation,37,37,0.072552,0.677675,0.249773,neutral
4,Public AI Companies,SoundHound AI Inc,33,33,0.102923,0.729596,0.167480,neutral
5,Public AI Companies,"Airship AI Holdings, Inc",31,31,0.326068,0.404746,0.269186,neutral
6,Public AI Companies,MarketBeat,28,28,0.138180,0.587851,0.273970,neutral
7,Public AI Companies,LLC Sells,22,22,0.114481,0.804952,0.080567,neutral
8,Public AI Companies,Pony AI Inc,22,22,0.135138,0.724096,0.140767,neutral
9,Public AI Companies,Bullfrog AI Holdings Inc,21,21,0.255322,0.440986,0.303692,positive
10,Public AI Companies,"SoundHound AI, Inc",21,21,0.550131,0.166908,0.282960,negative
11,Public AI Companies,"Bullfrog AI Holdings, Inc",20,20,0.178209,0.705966,0.115825,neutral
12,Public AI Companies,Vanguard Group Inc,20,20,0.055620,0.271813,0.672567,positive
13,Public AI Companies,Alphabet Inc,18,18,0.168246,0.713894,0.117860,neutral
14,Public AI Companies,NYSEARCA,18,18,0.239160,0.335898,0.424942,positive
15,Public AI Companies,State Street Corp,18,18,0.003133,0.147008,0.849859,positive
16,Public AI Companies,WiseAvoid,18,18,0.004467,0.990438,0.005095,neutral
17,Public AI Companies,Airship AI Holdings Inc,16,16,0.153517,0.659768,0.186715,neutral
18,Public AI Companies,BlackRock Inc,16,16,0.015510,0.448262,0.536228,positive
19,Public AI Companies,Citigroup Inc,16,16,0.118709,0.818548,0.062743,neutral

Topic: Publishing & Intellectual Property

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Publishing & Intellectual Property,Google,303,303,0.169353,0.639666,0.190981,neutral
1,Publishing & Intellectual Property,Cox Media Group,269,269,0.011635,0.981099,0.007265,neutral
2,Publishing & Intellectual Property,Cox Media Group Television,263,263,0.047535,0.937098,0.015368,neutral
3,Publishing & Intellectual Property,Microsoft,210,210,0.227568,0.575037,0.197395,neutral
4,Publishing & Intellectual Property,Amazon,152,152,0.265035,0.496873,0.238092,neutral
5,Publishing & Intellectual Property,Facebook,88,88,0.057466,0.891584,0.050951,neutral
6,Publishing & Intellectual Property,Instagram,75,75,0.156068,0.792501,0.051431,neutral
7,Publishing & Intellectual Property,Meta,75,75,0.233879,0.674793,0.091328,neutral
8,Publishing & Intellectual Property,Cox Media Group(Opens,72,72,0.030501,0.921832,0.047667,neutral
9,Publishing & Intellectual Property,Apple,64,64,0.121109,0.633679,0.245213,neutral
10,Publishing & Intellectual Property,Nvidia,59,59,0.294732,0.322426,0.382842,positive
11,Publishing & Intellectual Property,95.5 WSB,58,58,0.131106,0.745609,0.123285,neutral
12,Publishing & Intellectual Property,The Associated Press,55,55,0.209812,0.746767,0.043421,neutral
13,Publishing & Intellectual Property,Opens,53,53,0.074634,0.813839,0.111527,neutral
14,Publishing & Intellectual Property,Cox Enterprises,48,48,0.124360,0.743724,0.131916,neutral
15,Publishing & Intellectual Property,WHIO Radio,45,45,0.108762,0.811477,0.079761,neutral
16,Publishing & Intellectual Property,WHIO TV 7,44,44,0.076108,0.847632,0.076260,neutral
17,Publishing & Intellectual Property,WSOC TV,44,44,0.128389,0.818487,0.053124,neutral
18,Publishing & Intellectual Property,APCredit,36,36,0.081546,0.767483,0.150970,neutral
19,Publishing & Intellectual Property,Trump,36,36,0.322487,0.646476,0.031036,neutral

Topic: Technology Industry News

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Technology Industry News,Google,322,322,0.223937,0.414761,0.361301,neutral
1,Technology Industry News,Microsoft,172,172,0.266410,0.400980,0.332610,neutral
2,Technology Industry News,Amazon,133,133,0.237846,0.340833,0.421321,positive
3,Technology Industry News,Meta,87,87,0.231492,0.444552,0.323956,neutral
4,Technology Industry News,Nvidia,78,78,0.195453,0.362974,0.441572,positive
5,Technology Industry News,Apple,72,72,0.194503,0.426804,0.378693,neutral
6,Technology Industry News,Instagram,29,29,0.271810,0.434285,0.293904,neutral
7,Technology Industry News,AMD,28,28,0.310589,0.234084,0.455327,positive
8,Technology Industry News,Intel,27,27,0.243651,0.297578,0.458771,positive
9,Technology Industry News,Meta Platforms Inc,27,27,0.410295,0.207078,0.382627,positive
10,Technology Industry News,Apple Inc,25,25,0.258734,0.356237,0.385029,neutral
11,Technology Industry News,Tesla,24,24,0.163934,0.449344,0.386722,positive
12,Technology Industry News,Samsung,23,23,0.281510,0.378828,0.339662,neutral
13,Technology Industry News,Oracle,22,22,0.110453,0.352769,0.536779,positive
14,Technology Industry News,Salesforce,22,22,0.155639,0.471872,0.372490,neutral
15,Technology Industry News,IBM,21,21,0.101754,0.655022,0.243224,neutral
16,Technology Industry News,Nvidia Corp,20,20,0.371134,0.211814,0.417052,positive
17,Technology Industry News,Altman,18,18,0.397056,0.507706,0.095238,neutral
18,Technology Industry News,Anthropic,18,18,0.153751,0.549573,0.296676,neutral
19,Technology Industry News,TechRadar,16,16,0.296773,0.363149,0.340079,positive

Topic: Workforce & Compensation

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Workforce & Compensation,Google,973,973,0.003874,0.990660,0.005466,neutral
1,Workforce & Compensation,Location,822,822,0.002911,0.991805,0.005283,neutral
2,Workforce & Compensation,Data Scientist,630,630,0.003208,0.992167,0.004626,neutral
3,Workforce & Compensation,Levels Fyi Inc.ChangeDownload,300,300,0.004183,0.969771,0.026046,neutral
4,Workforce & Compensation,Levels.fyi,276,276,0.002913,0.992191,0.004896,neutral
5,Workforce & Compensation,FAANG,150,150,0.007367,0.950661,0.041972,neutral
6,Workforce & Compensation,ExperienceTotal,97,97,0.002560,0.987344,0.010096,neutral
7,Workforce & Compensation,Heatmap,82,82,0.003353,0.989988,0.006659,neutral
8,Workforce & Compensation,LinkedIn,52,52,0.011191,0.982386,0.006424,neutral
9,Workforce & Compensation,Data Science,30,30,0.003038,0.991096,0.005866,neutral
10,Workforce & Compensation,Data Scientist Salary,25,25,0.003317,0.991786,0.004897,neutral
11,Workforce & Compensation,FacebookRelated,18,18,0.002997,0.989843,0.007160,neutral
12,Workforce & Compensation,JobsNo,15,15,0.004408,0.989292,0.006301,neutral
13,Workforce & Compensation,SalaryAdded,15,15,0.003539,0.990999,0.005462,neutral
14,Workforce & Compensation,Amazon,12,12,0.005155,0.982488,0.012356,neutral
15,Workforce & Compensation,Software Engineer,12,12,0.003375,0.991809,0.004815,neutral
16,Workforce & Compensation,Argo AIRelated CompaniesTableau,10,10,0.003118,0.990167,0.006714,neutral
17,Workforce & Compensation,CompaniesAsure,10,10,0.002851,0.989712,0.007437,neutral
18,Workforce & Compensation,MicrosoftRelated CompaniesFive9OracleServiceNo...,9,9,0.002742,0.989904,0.007355,neutral
19,Workforce & Compensation,Capital OneRelated,8,8,0.002628,0.989337,0.008035,neutral

In [84]:
# Top technologies by topic
technology_by_topic = (
    absa_df[absa_df["aspect_type"] == "technology"]
    .groupby(["bertopic_topic_label", "aspect"])
    .agg(
        n_mentions=("aspect", "size"),
        n_unique_articles=("url", "nunique"),
        prob_negative=("prob_negative", "mean"),
        prob_neutral=("prob_neutral", "mean"),
        prob_positive=("prob_positive", "mean"),
        dominant_sentiment=("sentiment", safe_mode)
    )
    .reset_index()
)

# Sort so the most-mentioned technologies appear first within each topic
technology_by_topic = technology_by_topic.sort_values(
    ["bertopic_topic_label", "n_mentions"],
    ascending=[True, False]
)

# Dictionary of dataframes: {topic: dataframe}
technology_topic_dfs = {
    topic: df.head(TOP_K).reset_index(drop=True)
    for topic, df in technology_by_topic.groupby("bertopic_topic_label")
}

# Display results
for topic, df_topic in technology_topic_dfs.items():
    print(f"\nTopic: {topic}")
    display(df_topic)

Topic: AI Market Commentary

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,AI Market Commentary,artificial intelligence,664,664,0.092807,0.445029,0.462164,positive
1,AI Market Commentary,generative ai,187,187,0.055935,0.282632,0.661433,positive
2,AI Market Commentary,ai model,168,168,0.071579,0.305471,0.622949,positive
3,AI Market Commentary,large language model,123,123,0.045672,0.293216,0.661112,positive
4,AI Market Commentary,machine learning,88,88,0.007129,0.259880,0.732991,positive
5,AI Market Commentary,chatbot,63,63,0.099775,0.480155,0.420070,neutral
6,AI Market Commentary,robotics,58,58,0.118923,0.307892,0.573185,positive
7,AI Market Commentary,autonomous driving,21,21,0.087651,0.273008,0.639341,positive
8,AI Market Commentary,foundation model,15,15,0.002401,0.374357,0.623241,positive
9,AI Market Commentary,computer vision,12,12,0.019746,0.422392,0.557862,positive
10,AI Market Commentary,natural language processing,7,7,0.001856,0.601001,0.397143,neutral
11,AI Market Commentary,neural network,7,7,0.002214,0.388920,0.608866,positive
12,AI Market Commentary,fine-tuning,5,5,0.002146,0.274125,0.723729,positive
13,AI Market Commentary,multimodal ai,5,5,0.002004,0.251142,0.746854,positive
14,AI Market Commentary,deep learning,4,4,0.075776,0.183426,0.740798,positive
15,AI Market Commentary,reinforcement learning,4,4,0.002859,0.287608,0.709532,positive
16,AI Market Commentary,retrieval-augmented generation,2,2,0.001414,0.090309,0.908277,positive
17,AI Market Commentary,transformer,1,1,0.001582,0.164285,0.834133,positive

Topic: African Technology Development

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,African Technology Development,artificial intelligence,782,782,0.092681,0.649772,0.257547,neutral
1,African Technology Development,machine learning,228,228,0.064592,0.747435,0.187973,neutral
2,African Technology Development,generative ai,175,175,0.114367,0.593330,0.292303,neutral
3,African Technology Development,chatbot,168,168,0.145653,0.545185,0.309162,neutral
4,African Technology Development,ai model,154,154,0.149050,0.573921,0.277030,neutral
5,African Technology Development,large language model,108,108,0.106003,0.691588,0.202409,neutral
6,African Technology Development,robotics,68,68,0.081263,0.540423,0.378314,neutral
7,African Technology Development,deep learning,31,31,0.091560,0.655554,0.252887,neutral
8,African Technology Development,natural language processing,31,31,0.140363,0.580468,0.279169,neutral
9,African Technology Development,computer vision,23,23,0.086364,0.481865,0.431771,positive
10,African Technology Development,fine-tuning,12,12,0.083572,0.591374,0.325054,neutral
11,African Technology Development,foundation model,11,11,0.143521,0.524714,0.331765,neutral
12,African Technology Development,transformer,11,11,0.079656,0.688764,0.231581,neutral
13,African Technology Development,neural network,10,10,0.010959,0.585572,0.403470,positive
14,African Technology Development,reinforcement learning,8,8,0.117112,0.715238,0.167650,neutral
15,African Technology Development,autonomous driving,5,5,0.005724,0.717168,0.277108,neutral
16,African Technology Development,retrieval-augmented generation,5,5,0.004636,0.675855,0.319509,neutral
17,African Technology Development,prompt engineering,2,2,0.004797,0.815042,0.180161,neutral
18,African Technology Development,supervised learning,1,1,0.002699,0.991849,0.005452,neutral
19,African Technology Development,transformer model,1,1,0.002178,0.097199,0.900623,positive

Topic: Business Operations & Enterprise Automation

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Business Operations & Enterprise Automation,artificial intelligence,944,944,0.027461,0.528330,0.444210,neutral
1,Business Operations & Enterprise Automation,machine learning,543,543,0.018357,0.530581,0.451062,neutral
2,Business Operations & Enterprise Automation,generative ai,511,511,0.022918,0.570971,0.406111,neutral
3,Business Operations & Enterprise Automation,large language model,304,304,0.018136,0.563497,0.418367,neutral
4,Business Operations & Enterprise Automation,ai model,228,228,0.024500,0.514005,0.461495,neutral
5,Business Operations & Enterprise Automation,deep learning,143,143,0.015513,0.414691,0.569796,positive
6,Business Operations & Enterprise Automation,computer vision,130,130,0.007597,0.564458,0.427945,neutral
7,Business Operations & Enterprise Automation,natural language processing,130,130,0.019080,0.431182,0.549738,positive
8,Business Operations & Enterprise Automation,chatbot,119,119,0.055631,0.543846,0.400523,neutral
9,Business Operations & Enterprise Automation,robotics,70,70,0.012838,0.574295,0.412867,neutral
10,Business Operations & Enterprise Automation,neural network,65,65,0.002097,0.459007,0.538896,positive
11,Business Operations & Enterprise Automation,foundation model,37,37,0.013287,0.511010,0.475703,positive
12,Business Operations & Enterprise Automation,reinforcement learning,23,23,0.001763,0.603409,0.394828,neutral
13,Business Operations & Enterprise Automation,fine-tuning,22,22,0.003366,0.606217,0.390417,neutral
14,Business Operations & Enterprise Automation,autonomous driving,17,17,0.001916,0.488985,0.509100,positive
15,Business Operations & Enterprise Automation,transformer,17,17,0.007820,0.502355,0.489825,neutral
16,Business Operations & Enterprise Automation,vector database,12,12,0.004971,0.516817,0.478212,positive
17,Business Operations & Enterprise Automation,prompt engineering,11,11,0.001763,0.260349,0.737888,positive
18,Business Operations & Enterprise Automation,embeddings,10,10,0.002325,0.568365,0.429310,neutral
19,Business Operations & Enterprise Automation,supervised learning,7,7,0.001358,0.969191,0.029451,neutral

Topic: Consumer & Public Services

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Consumer & Public Services,artificial intelligence,5109,5109,0.173805,0.696613,0.129582,neutral
1,Consumer & Public Services,chatbot,2214,2214,0.211157,0.652135,0.136708,neutral
2,Consumer & Public Services,generative ai,1626,1626,0.210507,0.567538,0.221955,neutral
3,Consumer & Public Services,large language model,1041,1041,0.167884,0.691244,0.140872,neutral
4,Consumer & Public Services,ai model,910,910,0.241124,0.589514,0.169362,neutral
5,Consumer & Public Services,machine learning,480,480,0.134066,0.703576,0.162358,neutral
6,Consumer & Public Services,foundation model,179,179,0.219179,0.603795,0.177027,neutral
7,Consumer & Public Services,robotics,150,150,0.096643,0.715776,0.187581,neutral
8,Consumer & Public Services,computer vision,76,76,0.131008,0.738447,0.130546,neutral
9,Consumer & Public Services,natural language processing,70,70,0.044553,0.663777,0.291670,neutral
10,Consumer & Public Services,autonomous driving,65,65,0.175041,0.696703,0.128256,neutral
11,Consumer & Public Services,neural network,64,64,0.354737,0.616684,0.028579,neutral
12,Consumer & Public Services,transformer,60,60,0.035209,0.876706,0.088085,neutral
13,Consumer & Public Services,deep learning,48,48,0.090525,0.802708,0.106767,neutral
14,Consumer & Public Services,reinforcement learning,25,25,0.060252,0.817409,0.122339,neutral
15,Consumer & Public Services,fine-tuning,15,15,0.071669,0.747268,0.181063,neutral
16,Consumer & Public Services,prompt engineering,4,4,0.019650,0.711522,0.268828,neutral
17,Consumer & Public Services,supervised learning,4,4,0.005343,0.842092,0.152565,neutral
18,Consumer & Public Services,unsupervised learning,3,3,0.009449,0.827940,0.162611,neutral
19,Consumer & Public Services,embeddings,1,1,0.002291,0.863379,0.134330,neutral

Topic: Corporate AI Announcements

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Corporate AI Announcements,artificial intelligence,1833,1833,0.020175,0.526731,0.453094,neutral
1,Corporate AI Announcements,machine learning,869,869,0.018793,0.496064,0.485143,positive
2,Corporate AI Announcements,generative ai,719,719,0.029443,0.553366,0.417191,neutral
3,Corporate AI Announcements,ai model,414,414,0.038286,0.506986,0.454728,neutral
4,Corporate AI Announcements,large language model,386,386,0.039998,0.579015,0.380987,neutral
5,Corporate AI Announcements,natural language processing,331,331,0.009711,0.486531,0.503758,positive
6,Corporate AI Announcements,chatbot,283,283,0.022960,0.530205,0.446834,neutral
7,Corporate AI Announcements,deep learning,261,261,0.015498,0.528236,0.456266,neutral
8,Corporate AI Announcements,computer vision,216,216,0.010500,0.567628,0.421872,neutral
9,Corporate AI Announcements,robotics,214,214,0.009218,0.551895,0.438887,neutral
10,Corporate AI Announcements,neural network,104,104,0.005144,0.531723,0.463133,neutral
11,Corporate AI Announcements,retrieval-augmented generation,49,49,0.002543,0.584821,0.412637,neutral
12,Corporate AI Announcements,fine-tuning,44,44,0.040158,0.507096,0.452746,neutral
13,Corporate AI Announcements,reinforcement learning,39,39,0.002042,0.693993,0.303965,neutral
14,Corporate AI Announcements,prompt engineering,36,36,0.002958,0.581178,0.415864,neutral
15,Corporate AI Announcements,autonomous driving,33,33,0.002157,0.428709,0.569134,positive
16,Corporate AI Announcements,foundation model,26,26,0.033987,0.562276,0.403737,neutral
17,Corporate AI Announcements,transformer,25,25,0.002136,0.423624,0.574240,positive
18,Corporate AI Announcements,vector database,21,21,0.012079,0.415616,0.572305,positive
19,Corporate AI Announcements,multimodal ai,17,17,0.056519,0.506257,0.437223,positive

Topic: Cross-Industry AI News / Outliers

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Cross-Industry AI News / Outliers,artificial intelligence,21921,21921,0.128559,0.677669,0.193772,neutral
1,Cross-Industry AI News / Outliers,generative ai,8569,8569,0.138015,0.600155,0.261829,neutral
2,Cross-Industry AI News / Outliers,chatbot,7099,7099,0.199967,0.613968,0.186065,neutral
3,Cross-Industry AI News / Outliers,ai model,5933,5933,0.148886,0.601981,0.249133,neutral
4,Cross-Industry AI News / Outliers,large language model,5104,5104,0.116139,0.676594,0.207267,neutral
5,Cross-Industry AI News / Outliers,machine learning,4924,4924,0.057967,0.684275,0.257758,neutral
6,Cross-Industry AI News / Outliers,robotics,1605,1605,0.045388,0.704597,0.250016,neutral
7,Cross-Industry AI News / Outliers,deep learning,1032,1032,0.030617,0.690328,0.279054,neutral
8,Cross-Industry AI News / Outliers,natural language processing,1005,1005,0.026814,0.667620,0.305566,neutral
9,Cross-Industry AI News / Outliers,computer vision,850,850,0.028246,0.701825,0.269929,neutral
10,Cross-Industry AI News / Outliers,neural network,818,818,0.045370,0.738381,0.216249,neutral
11,Cross-Industry AI News / Outliers,foundation model,531,531,0.088795,0.590398,0.320807,neutral
12,Cross-Industry AI News / Outliers,fine-tuning,341,341,0.075418,0.633737,0.290845,neutral
13,Cross-Industry AI News / Outliers,prompt engineering,317,317,0.032900,0.641259,0.325841,neutral
14,Cross-Industry AI News / Outliers,transformer,311,311,0.060448,0.707009,0.232543,neutral
15,Cross-Industry AI News / Outliers,reinforcement learning,286,286,0.050093,0.740552,0.209356,neutral
16,Cross-Industry AI News / Outliers,retrieval-augmented generation,236,236,0.034332,0.692172,0.273496,neutral
17,Cross-Industry AI News / Outliers,autonomous driving,218,218,0.082627,0.486951,0.430422,neutral
18,Cross-Industry AI News / Outliers,multimodal ai,90,90,0.040164,0.592674,0.367162,neutral
19,Cross-Industry AI News / Outliers,supervised learning,69,69,0.031802,0.843154,0.125044,neutral

Topic: Cryptocurrency & Digital Assets

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Cryptocurrency & Digital Assets,artificial intelligence,145,145,0.020136,0.898314,0.081550,neutral
1,Cryptocurrency & Digital Assets,machine learning,117,117,0.062703,0.829801,0.107496,neutral
2,Cryptocurrency & Digital Assets,deep learning,45,45,0.004222,0.968677,0.027101,neutral
3,Cryptocurrency & Digital Assets,large language model,29,29,0.003031,0.977917,0.019052,neutral
4,Cryptocurrency & Digital Assets,ai model,21,21,0.022713,0.851081,0.126207,neutral
5,Cryptocurrency & Digital Assets,chatbot,12,12,0.002298,0.946232,0.051470,neutral
6,Cryptocurrency & Digital Assets,robotics,8,8,0.007277,0.658444,0.334278,neutral
7,Cryptocurrency & Digital Assets,natural language processing,5,5,0.001762,0.807236,0.191003,neutral
8,Cryptocurrency & Digital Assets,neural network,5,5,0.001483,0.662006,0.336510,neutral
9,Cryptocurrency & Digital Assets,generative ai,2,2,0.001349,0.845894,0.152758,neutral
10,Cryptocurrency & Digital Assets,embeddings,1,1,0.003452,0.976497,0.020052,neutral
11,Cryptocurrency & Digital Assets,fine-tuning,1,1,0.001304,0.990398,0.008298,neutral

Topic: Enterprise Software & Cybersecurity

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Enterprise Software & Cybersecurity,artificial intelligence,3093,3093,0.004284,0.961054,0.034662,neutral
1,Enterprise Software & Cybersecurity,generative ai,883,883,0.020573,0.558342,0.421085,neutral
2,Enterprise Software & Cybersecurity,machine learning,666,666,0.017968,0.496424,0.485608,neutral
3,Enterprise Software & Cybersecurity,large language model,520,520,0.017004,0.604578,0.378418,neutral
4,Enterprise Software & Cybersecurity,ai model,494,494,0.029723,0.509333,0.460944,neutral
5,Enterprise Software & Cybersecurity,robotics,226,226,0.006026,0.647051,0.346923,neutral
6,Enterprise Software & Cybersecurity,chatbot,204,204,0.021627,0.490762,0.487611,positive
7,Enterprise Software & Cybersecurity,deep learning,157,157,0.023659,0.493452,0.482889,positive
8,Enterprise Software & Cybersecurity,natural language processing,156,156,0.011833,0.498563,0.489604,neutral
9,Enterprise Software & Cybersecurity,computer vision,130,130,0.004818,0.526256,0.468925,neutral
10,Enterprise Software & Cybersecurity,neural network,74,74,0.025369,0.554154,0.420477,neutral
11,Enterprise Software & Cybersecurity,retrieval-augmented generation,62,62,0.017786,0.694949,0.287265,neutral
12,Enterprise Software & Cybersecurity,foundation model,58,58,0.017867,0.424351,0.557783,positive
13,Enterprise Software & Cybersecurity,fine-tuning,52,52,0.020380,0.485174,0.494446,positive
14,Enterprise Software & Cybersecurity,transformer,34,34,0.066422,0.518318,0.415260,neutral
15,Enterprise Software & Cybersecurity,reinforcement learning,29,29,0.010421,0.583447,0.406132,neutral
16,Enterprise Software & Cybersecurity,autonomous driving,28,28,0.002334,0.459347,0.538319,positive
17,Enterprise Software & Cybersecurity,multimodal ai,20,20,0.001765,0.453746,0.544489,positive
18,Enterprise Software & Cybersecurity,prompt engineering,20,20,0.008331,0.582467,0.409203,neutral
19,Enterprise Software & Cybersecurity,vector database,18,18,0.001920,0.534741,0.463339,positive

Topic: Enterprise Technology

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Enterprise Technology,artificial intelligence,36996,36996,0.113625,0.660615,0.225760,neutral
1,Enterprise Technology,generative ai,16727,16727,0.110887,0.624246,0.264867,neutral
2,Enterprise Technology,chatbot,13891,13891,0.165187,0.625878,0.208936,neutral
3,Enterprise Technology,ai model,13060,13060,0.124866,0.616745,0.258388,neutral
4,Enterprise Technology,large language model,10877,10877,0.098868,0.689957,0.211175,neutral
5,Enterprise Technology,machine learning,9112,9112,0.062668,0.660799,0.276533,neutral
6,Enterprise Technology,robotics,3607,3607,0.050694,0.738293,0.211012,neutral
7,Enterprise Technology,deep learning,2151,2151,0.051747,0.668049,0.280205,neutral
8,Enterprise Technology,natural language processing,2143,2143,0.036208,0.624256,0.339536,neutral
9,Enterprise Technology,neural network,1619,1619,0.058403,0.685807,0.255790,neutral
10,Enterprise Technology,computer vision,1576,1576,0.029029,0.697226,0.273745,neutral
11,Enterprise Technology,foundation model,1089,1089,0.085332,0.629537,0.285131,neutral
12,Enterprise Technology,fine-tuning,904,904,0.055944,0.666394,0.277662,neutral
13,Enterprise Technology,transformer,811,811,0.057218,0.703998,0.238784,neutral
14,Enterprise Technology,retrieval-augmented generation,652,652,0.031018,0.782430,0.186551,neutral
15,Enterprise Technology,reinforcement learning,595,595,0.059833,0.667555,0.272612,neutral
16,Enterprise Technology,prompt engineering,471,471,0.066070,0.712418,0.221512,neutral
17,Enterprise Technology,autonomous driving,445,445,0.070267,0.579612,0.350122,neutral
18,Enterprise Technology,multimodal ai,293,293,0.048542,0.632159,0.319299,neutral
19,Enterprise Technology,embeddings,172,172,0.037928,0.741735,0.220337,neutral

Topic: Financial Markets & Investing

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Financial Markets & Investing,artificial intelligence,2051,2051,0.118755,0.559792,0.321453,neutral
1,Financial Markets & Investing,generative ai,1112,1112,0.095296,0.486688,0.418016,neutral
2,Financial Markets & Investing,chatbot,645,645,0.132595,0.562486,0.304920,neutral
3,Financial Markets & Investing,ai model,602,602,0.093501,0.535113,0.371386,neutral
4,Financial Markets & Investing,large language model,587,587,0.087355,0.583825,0.328820,neutral
5,Financial Markets & Investing,machine learning,400,400,0.049699,0.504661,0.445640,neutral
6,Financial Markets & Investing,robotics,126,126,0.059761,0.493774,0.446466,positive
7,Financial Markets & Investing,natural language processing,61,61,0.015195,0.599367,0.385438,neutral
8,Financial Markets & Investing,deep learning,60,60,0.054045,0.611299,0.334655,neutral
9,Financial Markets & Investing,computer vision,58,58,0.040136,0.459299,0.500565,positive
10,Financial Markets & Investing,foundation model,56,56,0.078652,0.509849,0.411499,neutral
11,Financial Markets & Investing,autonomous driving,46,46,0.052626,0.422842,0.524531,positive
12,Financial Markets & Investing,neural network,39,39,0.041206,0.648968,0.309826,neutral
13,Financial Markets & Investing,transformer,36,36,0.125489,0.623626,0.250885,neutral
14,Financial Markets & Investing,fine-tuning,22,22,0.059283,0.582277,0.358440,neutral
15,Financial Markets & Investing,multimodal ai,13,13,0.108876,0.660539,0.230585,neutral
16,Financial Markets & Investing,reinforcement learning,11,11,0.005043,0.651624,0.343333,neutral
17,Financial Markets & Investing,transformer model,10,10,0.242897,0.536766,0.220337,neutral
18,Financial Markets & Investing,prompt engineering,6,6,0.013850,0.189199,0.796951,positive
19,Financial Markets & Investing,retrieval-augmented generation,6,6,0.001457,0.619701,0.378841,neutral

Topic: Financial Services & Business

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Financial Services & Business,artificial intelligence,3073,3073,0.143261,0.625550,0.231189,neutral
1,Financial Services & Business,chatbot,1153,1153,0.194757,0.612458,0.192785,neutral
2,Financial Services & Business,generative ai,1123,1123,0.154527,0.554715,0.290758,neutral
3,Financial Services & Business,ai model,926,926,0.128715,0.578045,0.293240,neutral
4,Financial Services & Business,large language model,777,777,0.120214,0.653174,0.226612,neutral
5,Financial Services & Business,machine learning,573,573,0.090840,0.603776,0.305384,neutral
6,Financial Services & Business,robotics,204,204,0.079624,0.629937,0.290439,neutral
7,Financial Services & Business,deep learning,120,120,0.043853,0.621806,0.334341,neutral
8,Financial Services & Business,natural language processing,107,107,0.059378,0.555960,0.384662,neutral
9,Financial Services & Business,neural network,98,98,0.060667,0.685457,0.253877,neutral
10,Financial Services & Business,computer vision,85,85,0.036214,0.622307,0.341479,neutral
11,Financial Services & Business,foundation model,83,83,0.145421,0.612287,0.242292,neutral
12,Financial Services & Business,transformer,75,75,0.101436,0.639589,0.258975,neutral
13,Financial Services & Business,fine-tuning,48,48,0.053970,0.642882,0.303147,neutral
14,Financial Services & Business,autonomous driving,46,46,0.141824,0.380678,0.477498,positive
15,Financial Services & Business,reinforcement learning,32,32,0.046125,0.682314,0.271561,neutral
16,Financial Services & Business,multimodal ai,17,17,0.031509,0.608525,0.359966,neutral
17,Financial Services & Business,prompt engineering,16,16,0.093818,0.738972,0.167210,neutral
18,Financial Services & Business,retrieval-augmented generation,14,14,0.001864,0.817729,0.180406,neutral
19,Financial Services & Business,transformer model,10,10,0.068375,0.546202,0.385423,neutral

Topic: Healthcare & Life Sciences

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Healthcare & Life Sciences,artificial intelligence,2226,2226,0.046137,0.678122,0.275741,neutral
1,Healthcare & Life Sciences,machine learning,872,872,0.034608,0.654124,0.311269,neutral
2,Healthcare & Life Sciences,ai model,597,597,0.066046,0.659681,0.274273,neutral
3,Healthcare & Life Sciences,generative ai,443,443,0.080589,0.596270,0.323141,neutral
4,Healthcare & Life Sciences,chatbot,366,366,0.124359,0.621205,0.254436,neutral
5,Healthcare & Life Sciences,large language model,353,353,0.067894,0.691395,0.240711,neutral
6,Healthcare & Life Sciences,deep learning,272,272,0.028721,0.604210,0.367069,neutral
7,Healthcare & Life Sciences,robotics,205,205,0.014960,0.812152,0.172889,neutral
8,Healthcare & Life Sciences,neural network,137,137,0.027557,0.713808,0.258635,neutral
9,Healthcare & Life Sciences,natural language processing,131,131,0.026164,0.545742,0.428094,neutral
10,Healthcare & Life Sciences,computer vision,120,120,0.018316,0.678432,0.303252,neutral
11,Healthcare & Life Sciences,foundation model,61,61,0.008278,0.637194,0.354528,neutral
12,Healthcare & Life Sciences,transformer,33,33,0.007049,0.757789,0.235162,neutral
13,Healthcare & Life Sciences,reinforcement learning,25,25,0.060973,0.688620,0.250407,neutral
14,Healthcare & Life Sciences,fine-tuning,20,20,0.103144,0.569044,0.327813,neutral
15,Healthcare & Life Sciences,supervised learning,18,18,0.006202,0.742465,0.251333,neutral
16,Healthcare & Life Sciences,multimodal ai,14,14,0.067729,0.667616,0.264655,neutral
17,Healthcare & Life Sciences,retrieval-augmented generation,8,8,0.090506,0.873509,0.035985,neutral
18,Healthcare & Life Sciences,transformer model,8,8,0.002031,0.609553,0.388416,neutral
19,Healthcare & Life Sciences,unsupervised learning,8,8,0.004967,0.978311,0.016722,neutral

Topic: Media, Journalism & Public Policy

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,"Media, Journalism & Public Policy",artificial intelligence,2151,2151,0.169976,0.742018,0.088006,neutral
1,"Media, Journalism & Public Policy",chatbot,708,708,0.251307,0.689464,0.059229,neutral
2,"Media, Journalism & Public Policy",generative ai,463,463,0.221775,0.669310,0.108915,neutral
3,"Media, Journalism & Public Policy",ai model,416,416,0.225717,0.657741,0.116541,neutral
4,"Media, Journalism & Public Policy",large language model,313,313,0.206325,0.719811,0.073864,neutral
5,"Media, Journalism & Public Policy",machine learning,152,152,0.241233,0.703692,0.055074,neutral
6,"Media, Journalism & Public Policy",robotics,60,60,0.022878,0.935913,0.041209,neutral
7,"Media, Journalism & Public Policy",neural network,45,45,0.004674,0.982107,0.013218,neutral
8,"Media, Journalism & Public Policy",reinforcement learning,19,19,0.080994,0.872026,0.046980,neutral
9,"Media, Journalism & Public Policy",natural language processing,13,13,0.057966,0.933990,0.008044,neutral
10,"Media, Journalism & Public Policy",autonomous driving,12,12,0.003433,0.989699,0.006868,neutral
11,"Media, Journalism & Public Policy",fine-tuning,11,11,0.918796,0.073369,0.007835,negative
12,"Media, Journalism & Public Policy",supervised learning,7,7,0.030788,0.933312,0.035900,neutral
13,"Media, Journalism & Public Policy",deep learning,6,6,0.109215,0.876217,0.014567,neutral
14,"Media, Journalism & Public Policy",foundation model,6,6,0.024809,0.393091,0.582100,neutral
15,"Media, Journalism & Public Policy",prompt engineering,5,5,0.001525,0.992489,0.005986,neutral
16,"Media, Journalism & Public Policy",transformer,5,5,0.004545,0.987560,0.007895,neutral
17,"Media, Journalism & Public Policy",retrieval-augmented generation,2,2,0.071882,0.917418,0.010700,neutral

Topic: Music & Entertainment

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Music & Entertainment,artificial intelligence,605,605,0.175050,0.733584,0.091366,neutral
1,Music & Entertainment,generative ai,216,216,0.200799,0.660314,0.138887,neutral
2,Music & Entertainment,ai model,168,168,0.234836,0.639582,0.125582,neutral
3,Music & Entertainment,chatbot,122,122,0.226665,0.714491,0.058845,neutral
4,Music & Entertainment,machine learning,69,69,0.034733,0.820258,0.145008,neutral
5,Music & Entertainment,large language model,42,42,0.143933,0.724024,0.132044,neutral
6,Music & Entertainment,robotics,19,19,0.017068,0.867754,0.115177,neutral
7,Music & Entertainment,neural network,18,18,0.031410,0.836330,0.132260,neutral
8,Music & Entertainment,natural language processing,10,10,0.002986,0.709560,0.287454,neutral
9,Music & Entertainment,deep learning,7,7,0.006833,0.596271,0.396896,neutral
10,Music & Entertainment,transformer,5,5,0.003406,0.842093,0.154501,neutral
11,Music & Entertainment,fine-tuning,4,4,0.031250,0.865721,0.103029,neutral
12,Music & Entertainment,foundation model,4,4,0.310608,0.532050,0.157342,neutral
13,Music & Entertainment,multimodal ai,4,4,0.127765,0.855013,0.017222,neutral
14,Music & Entertainment,prompt engineering,3,3,0.003527,0.980747,0.015726,neutral
15,Music & Entertainment,transformer model,3,3,0.003990,0.742399,0.253611,neutral
16,Music & Entertainment,reinforcement learning,2,2,0.002168,0.972518,0.025314,neutral
17,Music & Entertainment,computer vision,1,1,0.002736,0.993655,0.003608,neutral
18,Music & Entertainment,embedding model,1,1,0.002400,0.992163,0.005437,neutral
19,Music & Entertainment,retrieval-augmented generation,1,1,0.001837,0.948869,0.049294,neutral

Topic: Public AI Companies

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Public AI Companies,artificial intelligence,549,549,0.114383,0.634435,0.251182,neutral
1,Public AI Companies,robotics,163,163,0.110578,0.694336,0.195086,neutral
2,Public AI Companies,machine learning,142,142,0.050087,0.658096,0.291817,neutral
3,Public AI Companies,generative ai,17,17,0.148910,0.488538,0.362552,neutral
4,Public AI Companies,autonomous driving,5,5,0.002602,0.740241,0.257157,neutral
5,Public AI Companies,computer vision,5,5,0.076079,0.864560,0.059361,neutral
6,Public AI Companies,supervised learning,5,5,0.002788,0.987117,0.010095,neutral
7,Public AI Companies,unsupervised learning,5,5,0.002914,0.986895,0.010191,neutral
8,Public AI Companies,ai model,4,4,0.223883,0.410164,0.365954,neutral
9,Public AI Companies,chatbot,4,4,0.023922,0.893895,0.082183,neutral
10,Public AI Companies,large language model,4,4,0.163484,0.609689,0.226827,neutral
11,Public AI Companies,deep learning,3,3,0.308082,0.285688,0.406230,neutral
12,Public AI Companies,natural language processing,3,3,0.176385,0.475891,0.347723,negative
13,Public AI Companies,retrieval-augmented generation,2,2,0.003400,0.992975,0.003625,neutral
14,Public AI Companies,foundation model,1,1,0.001930,0.016436,0.981634,positive

Topic: Publishing & Intellectual Property

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Publishing & Intellectual Property,artificial intelligence,1006,1006,0.207513,0.638376,0.154111,neutral
1,Publishing & Intellectual Property,chatbot,390,390,0.269421,0.588842,0.141736,neutral
2,Publishing & Intellectual Property,generative ai,345,345,0.207578,0.621244,0.171178,neutral
3,Publishing & Intellectual Property,ai model,196,196,0.255186,0.615162,0.129653,neutral
4,Publishing & Intellectual Property,large language model,151,151,0.214903,0.705518,0.079578,neutral
5,Publishing & Intellectual Property,machine learning,58,58,0.091198,0.709284,0.199518,neutral
6,Publishing & Intellectual Property,foundation model,35,35,0.272902,0.699320,0.027778,neutral
7,Publishing & Intellectual Property,computer vision,18,18,0.020231,0.746323,0.233446,neutral
8,Publishing & Intellectual Property,robotics,17,17,0.237788,0.654322,0.107891,neutral
9,Publishing & Intellectual Property,neural network,12,12,0.046473,0.885005,0.068523,neutral
10,Publishing & Intellectual Property,deep learning,8,8,0.068204,0.660497,0.271299,neutral
11,Publishing & Intellectual Property,natural language processing,7,7,0.002723,0.383789,0.613489,positive
12,Publishing & Intellectual Property,autonomous driving,4,4,0.118056,0.705815,0.176129,neutral
13,Publishing & Intellectual Property,fine-tuning,4,4,0.251510,0.736423,0.012067,neutral
14,Publishing & Intellectual Property,transformer,4,4,0.002098,0.978057,0.019845,neutral
15,Publishing & Intellectual Property,reinforcement learning,2,2,0.002035,0.942593,0.055372,neutral
16,Publishing & Intellectual Property,multimodal ai,1,1,0.001257,0.962263,0.036480,neutral
17,Publishing & Intellectual Property,retrieval-augmented generation,1,1,0.007185,0.137492,0.855322,positive

Topic: Technology Industry News

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Technology Industry News,artificial intelligence,922,922,0.236713,0.344931,0.418356,positive
1,Technology Industry News,generative ai,384,384,0.166299,0.399129,0.434572,positive
2,Technology Industry News,ai model,326,326,0.197003,0.410244,0.392752,neutral
3,Technology Industry News,machine learning,309,309,0.129159,0.509292,0.361549,neutral
4,Technology Industry News,large language model,214,214,0.168749,0.521958,0.309293,neutral
5,Technology Industry News,chatbot,171,171,0.265144,0.461854,0.273002,neutral
6,Technology Industry News,robotics,61,61,0.109708,0.483778,0.406513,neutral
7,Technology Industry News,natural language processing,58,58,0.140434,0.499126,0.360440,neutral
8,Technology Industry News,multimodal ai,38,38,0.079630,0.333379,0.586991,positive
9,Technology Industry News,neural network,34,34,0.031167,0.618108,0.350725,neutral
10,Technology Industry News,prompt engineering,25,25,0.088170,0.644808,0.267022,neutral
11,Technology Industry News,deep learning,21,21,0.006873,0.622814,0.370314,neutral
12,Technology Industry News,foundation model,20,20,0.067899,0.424433,0.507669,positive
13,Technology Industry News,retrieval-augmented generation,20,20,0.066868,0.689865,0.243267,neutral
14,Technology Industry News,fine-tuning,17,17,0.232673,0.441234,0.326093,neutral
15,Technology Industry News,reinforcement learning,17,17,0.095274,0.431173,0.473553,positive
16,Technology Industry News,autonomous driving,15,15,0.065942,0.250415,0.683643,positive
17,Technology Industry News,computer vision,13,13,0.172964,0.536317,0.290720,neutral
18,Technology Industry News,vector database,10,10,0.130357,0.717307,0.152336,neutral
19,Technology Industry News,embeddings,9,9,0.002594,0.639000,0.358407,neutral

Topic: Workforce & Compensation

,bertopic_topic_label,aspect,n_mentions,n_unique_articles,prob_negative,prob_neutral,prob_positive,dominant_sentiment
0,Workforce & Compensation,machine learning,29,29,0.002876,0.963114,0.034010,neutral
1,Workforce & Compensation,large language model,21,21,0.003436,0.990246,0.006318,neutral
2,Workforce & Compensation,robotics,3,3,0.002439,0.990912,0.006649,neutral
3,Workforce & Compensation,artificial intelligence,2,2,0.001767,0.603225,0.395009,neutral
4,Workforce & Compensation,ai model,1,1,0.006433,0.902655,0.090912,neutral
5,Workforce & Compensation,computer vision,1,1,0.002493,0.978031,0.019476,neutral
6,Workforce & Compensation,generative ai,1,1,0.001458,0.988154,0.010389,neutral
7,Workforce & Compensation,reinforcement learning,1,1,0.001325,0.934061,0.064614,neutral
8,Workforce & Compensation,supervised learning,1,1,0.001747,0.045404,0.952849,positive

In [85]:
# File paths
# Main file paths
absa_detail_path = os.path.join(OUTPUT_DIR, "absa_detailed_aspects.parquet")
aspect_agg_path = os.path.join(OUTPUT_DIR, "absa_aspect_aggregate.parquet")
company_aspect_path = os.path.join(OUTPUT_DIR, "absa_company_aspects.parquet")
technology_aspect_path = os.path.join(OUTPUT_DIR, "absa_technology_aspects.parquet")
article_sent_path = os.path.join(OUTPUT_DIR, "article_sentiment.parquet")
topic_sent_path = os.path.join(OUTPUT_DIR, "topic_sentiment.parquet")
company_by_topic_path = os.path.join(OUTPUT_DIR, "company_by_topic.parquet")
technology_by_topic_path = os.path.join(OUTPUT_DIR, "technology_by_topic.parquet")

# Save main tables
absa_df.to_parquet(absa_detail_path, index=False)

aspect_agg_df.to_parquet(aspect_agg_path, index=False)
company_aspect_agg_df.to_parquet(company_aspect_path, index=False)
technology_aspect_agg_df.to_parquet(technology_aspect_path, index=False)

article_sentiment_df.to_parquet(article_sent_path, index=False)
topic_sentiment_df.to_parquet(topic_sent_path, index=False)

# Save full by-topic tables
company_by_topic.to_parquet(company_by_topic_path, index=False)
technology_by_topic.to_parquet(technology_by_topic_path, index=False)

# Save each topic-specific company table
company_topic_dir = os.path.join(OUTPUT_DIR, "top_companies_by_topic")
os.makedirs(company_topic_dir, exist_ok=True)

for topic, df_topic in company_topic_dfs.items():
    topic_slug = re.sub(r"[^\w\s-]", "", str(topic).lower())
    topic_slug = re.sub(r"\s+", "_", topic_slug.strip())
    topic_slug = re.sub(r"_+", "_", topic_slug)

    path = os.path.join(company_topic_dir, f"{topic_slug}.parquet")
    df_topic.to_parquet(path, index=False)

# Save each topic-specific technology table
technology_topic_dir = os.path.join(OUTPUT_DIR, "top_technologies_by_topic")
os.makedirs(technology_topic_dir, exist_ok=True)

for topic, df_topic in technology_topic_dfs.items():
    topic_slug = re.sub(r"[^\w\s-]", "", str(topic).lower())
    topic_slug = re.sub(r"\s+", "_", topic_slug.strip())
    topic_slug = re.sub(r"_+", "_", topic_slug)

    path = os.path.join(technology_topic_dir, f"{topic_slug}.parquet")
    df_topic.to_parquet(path, index=False)

print("\nSaved files:")
print(absa_detail_path)
print(aspect_agg_path)
print(company_aspect_path)
print(technology_aspect_path)
print(article_sent_path)
print(topic_sent_path)
print(company_by_topic_path)
print(technology_by_topic_path)
print(company_topic_dir)
print(technology_topic_dir)

Saved files:
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/absa_detailed_aspects.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/absa_aspect_aggregate.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/absa_company_aspects.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/absa_technology_aspects.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/article_sentiment.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/topic_sentiment.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/company_by_topic.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/technology_by_topic.parquet
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/top_companies_by_topic
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/top_technologies_by_topic

In [86]:
# Graphs
sentiment_order = ["negative", "neutral", "positive"]

def plot_grouped_sentiment_bars(
    counts_df,
    category_col,
    title,
    save_path,
    figsize=(12, 6),
    rotate_xticks=45
):
    if counts_df.empty:
        return

    pivot_df = (
        counts_df.pivot(index=category_col, columns="sentiment", values="count")
        .fillna(0)
        .astype(int)
    )

    pivot_df = ensure_sentiment_columns(pivot_df, sentiments=sentiment_order)
    pivot_df = pivot_df.reset_index()

    labels = wrap_or_shorten_labels(pivot_df[category_col].tolist(), max_len=35)
    x = np.arange(len(labels))
    width = 0.25

    plt.figure(figsize=figsize)
    plt.bar(x - width, pivot_df["negative"], width=width, label="Negative")
    plt.bar(x,         pivot_df["neutral"],  width=width, label="Neutral")
    plt.bar(x + width, pivot_df["positive"], width=width, label="Positive")

    plt.xticks(x, labels, rotation=rotate_xticks, ha="right")
    plt.ylabel("Count")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()

def plot_single_topic_article_sentiment(topic_display, topic_article_counts, save_path):
    vals = [int(topic_article_counts.get(s, 0)) for s in sentiment_order]

    plt.figure(figsize=(8, 5))
    plt.bar(["Negative", "Neutral", "Positive"], vals)
    plt.ylabel("# of Articles")
    plt.title(f"Article Sentiment Counts\n{shorten(str(topic_display), width=90, placeholder='...')}")
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()

def plot_sentiment_proportion_over_time(prop_df, topic_display, save_path, freq_label="Month"):
    if prop_df.empty:
        return

    plt.figure(figsize=(12, 6))
    plt.plot(prop_df["time_period"], prop_df["negative"], marker="o", label="Negative")
    plt.plot(prop_df["time_period"], prop_df["neutral"], marker="o", label="Neutral")
    plt.plot(prop_df["time_period"], prop_df["positive"], marker="o", label="Positive")

    plt.ylim(0, 1)
    plt.ylabel("Proportion of Articles")
    plt.xlabel(freq_label)
    plt.title(f"Sentiment Proportions Over Time\n{shorten(str(topic_display), width=90, placeholder='...')}")
    plt.legend()
    plt.xticks(rotation=45, ha="right")
    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches="tight")
    plt.close()

In [87]:
# Build topic num label matching
topic_meta = (
    bertopic_small[["bertopic_topic_text", "bertopic_topic_label"]]
    .drop_duplicates()
    .rename(columns={"bertopic_topic_text": "topic_num"})
    .copy()
)

topic_num_map = dict(zip(topic_meta["bertopic_topic_label"], topic_meta["topic_num"]))

In [88]:
# Build graph source tables
# A) Article-level sentiment counts by topic
article_sentiment_counts_by_topic = (
    article_sentiment_df.groupby(["dominant_topic", "dominant_sentiment"])
    .size()
    .reset_index(name="count")
)
article_sentiment_counts_by_topic.to_parquet(
    os.path.join(OUTPUT_DIR, "article_topic_sentiment_counts.parquet"),
    index=False
)

# B) Company sentiment counts by topic + company
topic_company_sentiment_counts = (
    absa_df[absa_df["aspect_type"] == "company"]
    .groupby(["bertopic_topic_label", "aspect", "sentiment"])
    .size()
    .reset_index(name="count")
)
topic_company_sentiment_counts.to_parquet(
    os.path.join(OUTPUT_DIR, "topic_company_sentiment_counts.parquet"),
    index=False
)

# C) Technology sentiment counts by topic + technology
topic_technology_sentiment_counts = (
    absa_df[absa_df["aspect_type"] == "technology"]
    .groupby(["bertopic_topic_label", "aspect", "sentiment"])
    .size()
    .reset_index(name="count")
)
topic_technology_sentiment_counts.to_parquet(
    os.path.join(OUTPUT_DIR, "topic_technology_sentiment_counts.parquet"),
    index=False
)

# D) Top 10 companies within each topic
topic_top10_companies = (
    absa_df[absa_df["aspect_type"] == "company"]
    .groupby(["bertopic_topic_label", "aspect"])
    .size()
    .reset_index(name="n_mentions")
    .sort_values(["bertopic_topic_label", "n_mentions"], ascending=[True, False])
    .groupby("bertopic_topic_label", group_keys=False)
    .head(10)
    .copy()
)
topic_top10_companies.to_parquet(
    os.path.join(OUTPUT_DIR, "topic_top10_companies.parquet"),
    index=False
)

# E) Top 10 technologies within each topic
topic_top10_technologies = (
    absa_df[absa_df["aspect_type"] == "technology"]
    .groupby(["bertopic_topic_label", "aspect"])
    .size()
    .reset_index(name="n_mentions")
    .sort_values(["bertopic_topic_label", "n_mentions"], ascending=[True, False])
    .groupby("bertopic_topic_label", group_keys=False)
    .head(10)
    .copy()
)
topic_top10_technologies.to_parquet(
    os.path.join(OUTPUT_DIR, "topic_top10_technologies.parquet"),
    index=False
)

In [89]:
# Time series sentiment proportions
article_sentiment_time_df = article_sentiment_df.copy()
article_sentiment_time_df["date"] = pd.to_datetime(article_sentiment_time_df["date"], errors="coerce")
article_sentiment_time_df = article_sentiment_time_df[
    article_sentiment_time_df["date"].notna()
].copy()

if len(article_sentiment_time_df) > 0:
    TIME_FREQ = "M"

    article_sentiment_time_df["time_period"] = (
        article_sentiment_time_df["date"]
        .dt.to_period(TIME_FREQ)
        .dt.to_timestamp()
    )

    topic_time_sentiment_counts = (
        article_sentiment_time_df.groupby(
            ["dominant_topic", "time_period", "dominant_sentiment"]
        )
        .size()
        .reset_index(name="count")
    )

    topic_time_sentiment_pivot = (
        topic_time_sentiment_counts
        .pivot_table(
            index=["dominant_topic", "time_period"],
            columns="dominant_sentiment",
            values="count",
            fill_value=0
        )
        .reset_index()
    )

    topic_time_sentiment_pivot = ensure_sentiment_columns(
        topic_time_sentiment_pivot.set_index(["dominant_topic", "time_period"]),
        sentiments=sentiment_order
    ).reset_index()

    topic_time_sentiment_pivot["total_articles"] = (
        topic_time_sentiment_pivot["negative"] +
        topic_time_sentiment_pivot["neutral"] +
        topic_time_sentiment_pivot["positive"]
    )

    for s in sentiment_order:
        topic_time_sentiment_pivot[f"{s}_prop"] = np.where(
            topic_time_sentiment_pivot["total_articles"] > 0,
            topic_time_sentiment_pivot[s] / topic_time_sentiment_pivot["total_articles"],
            0.0
        )

    topic_time_sentiment_pivot.to_parquet(
        os.path.join(OUTPUT_DIR, "topic_time_sentiment_proportions.parquet"),
        index=False
    )
else:
    topic_time_sentiment_pivot = pd.DataFrame()
    print("No valid date column found. Skipping time graphs.")

In [93]:
# Create graph files
all_topics = sorted(article_sentiment_df["dominant_topic"].dropna().astype(str).unique())

saved_topic_article_graphs = []
saved_topic_company_graphs = []
saved_topic_technology_graphs = []
saved_topic_time_graphs = []

for topic_label in tqdm(all_topics, total=len(all_topics), desc="Saving topic graphs"):
    topic_num = topic_num_map.get(topic_label, np.nan)

    if pd.notna(topic_num):
        topic_num_int = int(topic_num)
        topic_num_slug = f"topic_{topic_num_int}"
        topic_display = f"Topic {topic_num_int}: {topic_label}"
    else:
        topic_num_slug = "topic_unknown"
        topic_display = f"Topic Unknown: {topic_label}"

    topic_label_slug = slugify(topic_label)

    # ------------------------------------------
    # 1) Article sentiment counts for this topic
    # ------------------------------------------
    topic_article_counts = (
        article_sentiment_df.loc[
            article_sentiment_df["dominant_topic"] == topic_label,
            "dominant_sentiment"
        ]
        .value_counts()
    )

    topic_article_plot_path = os.path.join(
        TOPIC_GRAPH_DIR,
        f"{topic_num_slug}_{topic_label_slug}_article_sentiment_counts.png"
    )

    plot_single_topic_article_sentiment(
        topic_display=topic_display,
        topic_article_counts=topic_article_counts,
        save_path=topic_article_plot_path
    )
    saved_topic_article_graphs.append(topic_article_plot_path)

    # ------------------------------------------
    # 2) Top 10 companies sentiment counts
    # ------------------------------------------
    top_companies_this_topic = topic_top10_companies.loc[
        topic_top10_companies["bertopic_topic_label"] == topic_label,
        "aspect"
    ].tolist()

    if len(top_companies_this_topic) > 0:
        company_counts_this_topic = topic_company_sentiment_counts[
            (topic_company_sentiment_counts["bertopic_topic_label"] == topic_label) &
            (topic_company_sentiment_counts["aspect"].isin(top_companies_this_topic))
        ].copy()

        company_order = (
            topic_top10_companies.loc[
                topic_top10_companies["bertopic_topic_label"] == topic_label,
                ["aspect", "n_mentions"]
            ]
            .sort_values("n_mentions", ascending=False)["aspect"]
            .tolist()
        )

        company_counts_this_topic["aspect"] = pd.Categorical(
            company_counts_this_topic["aspect"],
            categories=company_order,
            ordered=True
        )
        company_counts_this_topic = company_counts_this_topic.sort_values("aspect")

        topic_company_plot_path = os.path.join(
            COMPANY_GRAPH_DIR,
            f"{topic_num_slug}_{topic_label_slug}_top10_companies_sentiment_counts.png"
        )

        plot_grouped_sentiment_bars(
            counts_df=company_counts_this_topic.rename(columns={"aspect": "company"}),
            category_col="company",
            title=f"Top 10 Companies by Sentiment Count\n{shorten(str(topic_display), width=90, placeholder='...')}",
            save_path=topic_company_plot_path,
            figsize=(14, 6),
            rotate_xticks=45
        )
        saved_topic_company_graphs.append(topic_company_plot_path)

    # ------------------------------------------
    # 3) Top 10 technologies sentiment counts
    # ------------------------------------------
    top_tech_this_topic = topic_top10_technologies.loc[
        topic_top10_technologies["bertopic_topic_label"] == topic_label,
        "aspect"
    ].tolist()

    if len(top_tech_this_topic) > 0:
        tech_counts_this_topic = topic_technology_sentiment_counts[
            (topic_technology_sentiment_counts["bertopic_topic_label"] == topic_label) &
            (topic_technology_sentiment_counts["aspect"].isin(top_tech_this_topic))
        ].copy()

        tech_order = (
            topic_top10_technologies.loc[
                topic_top10_technologies["bertopic_topic_label"] == topic_label,
                ["aspect", "n_mentions"]
            ]
            .sort_values("n_mentions", ascending=False)["aspect"]
            .tolist()
        )

        tech_counts_this_topic["aspect"] = pd.Categorical(
            tech_counts_this_topic["aspect"],
            categories=tech_order,
            ordered=True
        )
        tech_counts_this_topic = tech_counts_this_topic.sort_values("aspect")

        topic_tech_plot_path = os.path.join(
            TECH_GRAPH_DIR,
            f"{topic_num_slug}_{topic_label_slug}_top10_technologies_sentiment_counts.png"
        )

        plot_grouped_sentiment_bars(
            counts_df=tech_counts_this_topic.rename(columns={"aspect": "technology"}),
            category_col="technology",
            title=f"Top 10 Technologies by Sentiment Count\n{shorten(str(topic_display), width=90, placeholder='...')}",
            save_path=topic_tech_plot_path,
            figsize=(14, 6),
            rotate_xticks=45
        )
        saved_topic_technology_graphs.append(topic_tech_plot_path)

    # ------------------------------------------
    # 4) Sentiment proportions over time
    # ------------------------------------------
    if not topic_time_sentiment_pivot.empty:
        topic_time_df = topic_time_sentiment_pivot[
            topic_time_sentiment_pivot["dominant_topic"] == topic_label
        ].copy()

        if not topic_time_df.empty:
            topic_time_df = topic_time_df.sort_values("time_period")

            prop_df = topic_time_df[[
                "time_period", "negative_prop", "neutral_prop", "positive_prop"
            ]].rename(columns={
                "negative_prop": "negative",
                "neutral_prop": "neutral",
                "positive_prop": "positive"
            })

            topic_time_plot_path = os.path.join(
                TIME_GRAPH_DIR,
                f"{topic_num_slug}_{topic_label_slug}_sentiment_proportions_over_time.png"
            )

            plot_sentiment_proportion_over_time(
                prop_df=prop_df,
                topic_display=topic_display,
                save_path=topic_time_plot_path,
                freq_label="Month"
            )
            saved_topic_time_graphs.append(topic_time_plot_path)

Saving topic graphs:   0%|          | 0/18 [00:00<?, ?it/s]

In [94]:
# Graph saves
graph_manifest = pd.DataFrame({
    "graph_type": (
        ["topic_article_sentiment"] * len(saved_topic_article_graphs) +
        ["topic_top10_companies_sentiment"] * len(saved_topic_company_graphs) +
        ["topic_top10_technologies_sentiment"] * len(saved_topic_technology_graphs) +
        ["topic_sentiment_proportions_over_time"] * len(saved_topic_time_graphs)
    ),
    "file_path": (
        saved_topic_article_graphs +
        saved_topic_company_graphs +
        saved_topic_technology_graphs +
        saved_topic_time_graphs
    )
})

graph_manifest_path = os.path.join(OUTPUT_DIR, "graph_manifest.parquet")
graph_manifest.to_parquet(graph_manifest_path, index=False)

print("\nGraph folders:")
print("Topic article sentiment graphs:", TOPIC_GRAPH_DIR)
print("Topic top-10 company graphs:", COMPANY_GRAPH_DIR)
print("Topic top-10 technology graphs:", TECH_GRAPH_DIR)
print("Topic time-series sentiment graphs:", TIME_GRAPH_DIR)

print("\nSaved graph manifest:")
print(graph_manifest_path)

print("\nNumber of graphs saved:")
print("Article sentiment by topic:", len(saved_topic_article_graphs))
print("Top-10 companies by topic:", len(saved_topic_company_graphs))
print("Top-10 technologies by topic:", len(saved_topic_technology_graphs))
print("Sentiment proportions over time:", len(saved_topic_time_graphs))

display(graph_manifest.head(20))

Graph folders:
Topic article sentiment graphs: /content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/graphs/topic_article_sentiment
Topic top-10 company graphs: /content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/graphs/topic_top10_companies_sentiment
Topic top-10 technology graphs: /content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/graphs/topic_top10_technologies_sentiment
Topic time-series sentiment graphs: /content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/graphs/topic_sentiment_over_time

Saved graph manifest:
/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/absa_outputs/graph_manifest.parquet

Number of graphs saved:
Article sentiment by topic: 18
Top-10 companies by topic: 18
Top-10 technologies by topic: 18
Sentiment proportions over time: 18

,graph_type,file_path
0,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
1,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
2,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
3,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
4,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
5,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
6,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
7,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
8,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
9,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
10,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
11,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
12,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
13,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
14,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
15,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
16,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
17,topic_article_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
18,topic_top10_companies_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...
19,topic_top10_companies_sentiment,/content/drive/MyDrive/UChicago/Masters/Winter...