## NLP Final
### Part 2: Topic Detection - BERTopic/NMF Analysis
### Aren Mizuno
### March 12, 2026

In [1]:
# Imports
import pandas as pd
from google.colab import drive, files
from textwrap import shorten

In [2]:
# Mount drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
# Load df
base_path = "/content/drive/MyDrive/UChicago/Masters/Winter/NLP/Final Project/parquets/"
bertopic_text = pd.read_parquet(base_path + "bertopic_text.parquet")
bertopic_title = pd.read_parquet(base_path + "bertopic_title.parquet")
info_bertopic_text = pd.read_parquet(base_path + "bertopic_info_text.parquet")
info_bertopic_title = pd.read_parquet(base_path + "bertopic_info_title.parquet")
nmf_text = pd.read_parquet(base_path + "nmf_text.parquet")
nmf_title = pd.read_parquet(base_path + "nmf_title.parquet")
info_nmf_text = pd.read_parquet(base_path + "nmf_topic_info_text.parquet")
info_nmf_title = pd.read_parquet(base_path + "nmf_topic_info_title.parquet")

### BERTopic Text
18 topics labeled from -1 to 16.

In [9]:
# Load data
bertopic_text.head(2)

,url,date,title,text,bertopic_topic_text
0,https://blockworks.co/price/bad,2025-06-23,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",bad idea ai price bad market cap price today c...,10
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,This AI video of gymnastics might be the freak...,this ai video of gymnastics might be the freak...,0

In [10]:
# Load info data
info_bertopic_text.head(16)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,36170,-1_ai_news_new_data,"[ai, news, new, data, share, said, technology,...",[build an ai strategy that survives first cont...
1,0,61119,0_ai_news_new_data,"[ai, news, new, data, technology, google, inte...",[white house unveils ai rules to address safet...
2,1,6398,1_ago_news_hours ago_hours,"[ago, news, hours ago, hours, video, stories, ...",[professor attempts to fail students after fal...
3,2,5560,2_share_ai_market_india,"[share, ai, market, india, stock, bank, new, n...",[openai latest breakthrough is sobering realit...
4,3,3572,3_newswires_presswire_ein presswire_ein,"[newswires, presswire, ein presswire, ein, rel...",[biontech to host ai day as an edition of its ...
5,4,3270,4_ment_products_services_overviewview,"[ment, products, services, overviewview, consu...",[new fintech startup economyx ai uses machine ...
6,5,3067,5_health_ai_healthcare_medical,"[health, ai, healthcare, medical, patients, pa...",[artificial intelligence in oncology market to...
7,6,2808,6_share price_price_nasdaq_share,"[share price, price, nasdaq, share, symbols, m...",[stock split artificial intelligence ai stocks...
8,7,2802,7_npr_radio_public_news,"[npr, radio, public, news, schedule, donate, m...",[bubbling questions about the limitations of a...
9,8,1951,8_gray_ai_gray media_prnewswire,"[gray, ai, gray media, prnewswire, media group...",[genpact integrates generative ai into enterpr...
10,9,1513,9_salary_compensation_data scientist_scientist,"[salary, compensation, data scientist, scienti...",[rue gilt groupe data scientist salary levels ...
11,10,1461,10_price_ai_mexc_market,"[price, ai, mexc, market, prediction, trading,...",[ferret ai ferret price prediction price forec...
12,11,1201,11_new window_window_opens new_opens,"[new window, window, opens new, opens, new, wh...",[artificial intelligence is topic of upcoming ...
13,12,1177,12_shares_stock_nyse_nasdaq,"[shares, stock, nyse, nasdaq, llc, etf, price,...",[soundhound ai nasdaq soun trading up here wha...
14,13,1114,13_webpronews_ai_advertise_like,"[webpronews, ai, advertise, like, ientry, requ...",[of companies view ai as essential for operati...
15,14,1042,14_music_ai_song_spotify,"[music, ai, song, spotify, voice, new, news, a...",[beyond the beat how ai is dividing the music ...

In [11]:
# Representation words
for topic in sorted(info_bertopic_text["Topic"].unique()):
    rep = info_bertopic_text.loc[
        info_bertopic_text["Topic"] == topic, "Representation"
    ].iloc[0]

    print(f"\nTopic {topic}")
    print(rep)

Topic -1
['ai' 'news' 'new' 'data' 'share' 'said' 'technology' 'use' 'intelligence'
 'video']

Topic 0
['ai' 'news' 'new' 'data' 'technology' 'google' 'intelligence' 'chatgpt'
 'use' 'said']

Topic 1
['ago' 'news' 'hours ago' 'hours' 'video' 'stories' 'said' 'local' 'file'
 'ai']

Topic 2
['share' 'ai' 'market' 'india' 'stock' 'bank' 'new' 'news' 'company'
 'said']

Topic 3
['newswires' 'presswire' 'ein presswire' 'ein' 'releases' 'south' 'new'
 'north' 'distribution' 'ai']

Topic 4
['ment' 'products' 'services' 'overviewview' 'consumer' 'entertain ment'
 'entertain' 'general' 'technology' 'policy']

Topic 5
['health' 'ai' 'healthcare' 'medical' 'patients' 'patient' 'news' 'care'
 'cancer' 'research']

Topic 6
['share price' 'price' 'nasdaq' 'share' 'symbols' 'markets' 'market'
 'stocks' 'add' 'stock']

Topic 7
['npr' 'radio' 'public' 'news' 'schedule' 'donate' 'music' 'programs'
 'community' 'arts']

Topic 8
['gray' 'ai' 'gray media' 'prnewswire' 'media group' 'group' 'media'
 'press release' 'data' 'release']

Topic 9
['salary' 'compensation' 'data scientist' 'scientist' 'data' 'total'
 'salaries' 'pay' 'paying' 'total compensation']

Topic 10
['price' 'ai' 'mexc' 'market' 'prediction' 'trading' 'price prediction'
 'traded' 'usd' 'btc']

Topic 11
['new window' 'window' 'opens new' 'opens' 'new' 'whio' 'said' 'cox' 'ai'
 'feed opens']

Topic 12
['shares' 'stock' 'nyse' 'nasdaq' 'llc' 'etf' 'price' 'company'
 'soundhound' 'ai']

Topic 13
['webpronews' 'ai' 'advertise' 'like' 'ientry' 'request' 'advertising'
 'tech' 'marketing' 'cmspro']

Topic 14
['music' 'ai' 'song' 'spotify' 'voice' 'new' 'news' 'artists' 'ai music'
 'songs']

Topic 15
['africa' 'ai' 'nigeria' 'ago' 'news' 'african' 'ghana' 'bl premium' 'bl'
 'ago bl']

Topic 16
['nasdaq' 'add' 'symbols' 'quotes' 'market' 'available' 'markets'
 'currently' 'data' 'edit']

In [12]:
# Show example texts for each topic
for topic, group in bertopic_text.groupby("bertopic_topic_text"):
    print(f"\n{'='*60}")
    print(f"TOPIC {topic}")
    print(f"{'='*60}")

    for i, text in enumerate(group["text"].head(10), 1):
        snippet = shorten(str(text), width=400, placeholder="...")
        print(f"{i:>2}. {snippet}")

============================================================
TOPIC -1
============================================================
 1. zoom expands ai offering with ai companion and revenue accelerator skip to contentthu sep th citylifeunveiling new technologies and the power of ai ainewsspacetechnologysatellitescienceu contact technology zoom expands ai offering with ai companion and revenue accelerator byrobert andrew sep zoom video communications inc is embracing generative artificial intelligence ai by introducing two new...
 2. best ai prompts for risk managementproductsolutionslearnpricingenterprisecontact salessign uplog inmenuclose menuproductai built for youtasksdocsgoalswhiteboardsdashboardschatplatformrapidviews dbtemplatesintegrationsclickappshierarchyautomationssolutionssoftware developmentmarketingit and pmoengineeringdesignoperationsuse caseproject managementremote workcrmtypeenterprisestartupnon...
 3. chatgpt can chatbot preach good sermon hundreds attend church service generated by chatgpt to find out the economic times benchmarks nifty featured funds icici prudential india opportunities fund idcw return invest nowfeatured funds icici prudential large mid cap fund direct pla return invest nowenglish editionenglish edition today papersubscribesign inavail offer beat price...
 4. hasbro may be eyeing ai for dungeons dragons pedestrian tv lifehacker the chainsaw kotaku vice openair cinemas refinery the news of tomorrow today reviewscamerahere you ll find expert opinions on the latest cameras from canon nikon sony and plenty carour revheads bring you all you need to know on the coolest electric vehicles and cars available on the market entertainmentwe spend hours watching...
 5. taiwan puts companies behind china ai ambitions on export control list news channel admiral circle arrow play button stop button chevron right chevron left chevron up warning chevron left skinny chevron right skinny clock calendar play button cancel circle user twitter facebook youtube instagram email linkedin news santa barbara county san luis obispo county ventura county politics wildfires...
 6. immunoassay market to grow by usd billion driven by early diagnosis advances with ai impacting market trends technavio remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena...
 7. ai cctvs deployed in peru lima district for public safety tuesday january gmt remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices qutoes charts end of day stocks...
 8. copa libertadores artificial intelligence gives its winner of the duel between millonarios vs flamengo pledge times about us disclaimer for pledge times tuesday april pledge times gaming tech science lifestyle health gaming tech science lifestyle health no result view all result pledge times no result view all result copa libertadores artificial intelligence gives its winner of the duel between...
 9. ap source flyers trade captain claude giroux to panthers wsvn news miami news fort lauderdale wsvn news miami news fort lauderdale news local miami dade broward florida trending us politics help me howard hope and healing investigations special reports spotlight forecast interactive radar video forecast watches and warnings forecast models forecast cone hurricane tips app hurricane tracker app...
10. nvidia ceo suggests malaysia could be ai manufacturing hub as southeast asia expands data centers action news jax sectionswatch watch news video first alert hurricane center investigates election family focus florida lottery steals and deals opens in new window share your pics newsvote in our pollphoto gallerieselection this week in the action button linksnewsletter sign up opens in new window...

============================================================
TOPIC 0
============================================================
 1. this ai video of gymnastics might be the freakiest ve seen yet boing boing the posts wonderful products daily wonderful things about us writers and staff get satisfaction advertise thank you for reading the data you generate tos what you agree to thumbnails youtube thumbnail generator this ai video of gymnastics might be the freakiest ve seen yet jennifer sandlin mon jul screenshot luma ai sure...
 2. if using ai feels like chore try this boing boing the posts wonderful products daily wonderful things about us writers and staff get satisfaction advertise thank you for reading the data you generate tos what you agree to thumbnails youtube thumbnail generator if using ai feels like chore try this boing boing wed sep tl dr put all your ai tools in one place with lifetime subscription to minai...
 3. the road ahead how china ai foundation model is shaping the future of autonomous driving technology ir ao contidoven de novembro de vida da cidadepresentando as novas tecnolox as poder da ia ainoticiaespazotecnolox asat litecienciaeuacontacto noticia cami por diante como modelo da fundaci ai de china est dar forma ao futuro da tecnolox de conduci aut noma by novembro cami por diante como modelo...
 4. microsoft and nvidia to empower developers with windows ai studio ai ai microsoft and nvidia to empower developers with windows ai studio by microsoft and nvidia are joining forces to provide developers with the tools they need to run and customize ai models on windows pcs at the microsoft ignite event microsoft unveiled windows ai studio centralized hub where developers can access range of ai...
 5. google releases new chatbot bard as strong competitor to openai chatgpt wiessel un inhaltdi dezember stad liewenentdeckt nei technologien an kraaft vun ai aineiegkeetenspacetechnologysatellitescienceuskontakt ai neiegkeeten google ver ffentlecht den neie chatbot bard als staarke konkurrent fir openai chatgpt bymampho brescia dez google has recently unveiled its latest chatbot bard which is...
 6. pro ai thinking enhancing industrial environments with artificial intelligence fri aug th citylife the power of ai models ai drones military news satellite telephony satellite internet space technology contact news pro ai thinking enhancing industrial environments with artificial intelligence bymampho brescia aug in the rapidly developing industrial landscape paradigm shift called pro ai...
 7. state ags warn ai companies clean up your child safeguards crooks and liars support go ad free today ad free cltv on bluesky like us on facebook on twitter on mastodon on flipboard cltv on bluesky like us on facebook on twitter on mastodon on flipboard my ad free account support go ad free today subscriber latest sen warnock reminds mtp host who responsible for skyrocketing insurance premiums...
 8. qualcomm announces new ai chips in data center push shares surge dunya news videos shows live new downlink live pakistan cricket crime weird technology health fake news events reporting dunya digital pakistan cricket crime weird technology health fake news events reporting videos dunya digital our pick decades of oppression kashmiris continue struggle for freedom despite india repression turkey...
 9. openai goes in of suckers in hollywood exbulletin politics fashion tech connect with us exbulletin openai goes in of suckers in hollywood politics fashion tech openai goes in of suckers in hollywood openai wants to be star big bright shining star according to new report the influential ai company has spent recent months courting hollywood executives in hopes of convincing them that its the...
10. principles to help federal agencies adopt ai ethically and securely fedtech magazine skip to main content become an insider today to receive premium content mobile topics agencies features tips tactics video capital events about insider feds in the field news reviews telehealth the byte voices main topics agencies features tips tactics video capital events about insider feds in the field news...

============================================================
TOPIC 1
============================================================
 1. nc highway patrol utilizing ai to crack down on distracted driving cbs cbs com raleigh raleigh sponsored by toggle open navigation close navigation please enter term primary news wake county news durham county news north carolina news nc lottery cumberland county news johnston county news orange county news wayne county news local news that matters raleigh traffic live coverage honoring black...
 2. can chatbot preach good sermon hundreds attend church service generated by chatgpt to find out ksnf kode fourstateshomepage com ksnf kode fourstateshomepage com joplin joplin sponsored by toggle open navigation close navigation please enter term primary news local news crime joplin news webb city carthage neosho pittsburg missouri news kansas news northeast oklahoma northwest arkansas national...
 3. google unveils its chatgpt rival nation news komu com skip to main content you have permission to edit this article edit close facebook twitter linkedin youtube instagram dashboard logout my account dashboard profile saved items logout watch now about us meet the team advertise staying connected email local promote your event news releases award winning journalism terms of use news mid missouri...
 4. ftx bankruptcy also endangers founder philanthropic gifts join insider for freesign insearchnewswatch livelocal newsksat investigatescrimecourtsuvaldevote coronavirustexasbordersaqeducationconsumerbehind the kitchen doordatahealthnationalworldsolutionariestrust indexnews appweathertrafficpollenalertsdoppler radartraffic camswhatever the weatherweather historyclimatescience with sarahthermometer...
 5. meet tori ai for your fast food order nbc wcmh tv nbc wcmh tv columbus columbus sponsored by toggle open navigation close navigation please enter term primary watch tv schedule streaming guide nbc newscasts nbc on peacock nbc shows newsnation news local news better call nbc investigates the spectrum your local election hq intel in ohio download our apps nbc newsletters ohio news politics from...
 6. wanted an ai job that mostly doesn exist yet santa cruz sentinel all sections now thursday june th edition page close menunews news local news news alerts crime and public safety courts education election local politics environment health housing transportation national news neighborhoods aptos capitola north coast live oak san lorenzo valley santa cruz scotts valley soquel watsonville outdoors...
 7. thousands chatted with this ai virtual girlfriend then things got even weirder the news herald all sections now wednesday july th edition page close menunews news crime and public safety coronavirus politics schools traffic michigan news national news miprepzone opinion obituaries obituaries news obituaries things to do things to do regional lottery local events marketplace classifieds...
 8. tech firm baidu denies report that its ernie ai chatbot is linked to chinese military research wnct wnct greenville watch now to watch the latest greenville watch now sponsored by toggle open navigation close navigation please enter term primary news vote now on local north carolina coronavirus crime tracker your local election headquarters national russia and ukraine conflict southeast region...
 9. best of ces electric skates pet tech and ai for birds wtaj wtaj altoona altoona sponsored by toggle open navigation close navigation please enter term primary news local news pennsylvania news happy holidays national news news trending news lottery pa outdoors veterans voices destination pennsylvania penndot washington bureau food news making it matter daily newsletters bestreviews submit news...
10. microsoft new ai key is first big change to keyboards in decades wtrf wtrf triadelphia triadelphia sponsored by toggle open navigation close navigation please enter term primary news top stories local news watch west virginia ohio pennsylvania national news your local election hq emergencies politics from the hill washington dc border report tour press releases automotive news top stories some...

============================================================
TOPIC 2
============================================================
 1. equinix stock market leader positioned for ai growth but is it buy nasdaq eqix seeking alphaskip to contenthome page seeking alpha power to investorscreate free accountabout premiumfree newslettershomestock analysisstock ideasmarket outlookinvesting strategylong ideasipo analysiseditor pickscryptocurrencymarket newstop market newsnotable callson the moveearnings newsenergy stock newstech stock...
 2. chat gpt news latest news and headlines from australia and the worldwatch tvnewssportlifestyleentertainmentpropertyproduct reviewscouponsstandriveconnect with us nationalnswvicqldsawaacttasntlatestcoronaviruscrimetechnologyhealthexplainerstoday in historypoliticsworldasiaeuropenzukusachinarussia ukrainevideoslivetoday showcoronavirusextrason newsacacoronavirusextras minutescoronavirusextrason...
 3. mark zuckerberg lays down how meta will make money from its multi billion dollar ai bet meta platforms nasdaq meta benzingadeutschespa olindiaitalianofran aismy accountmy accountnotificationsoverview new watchlistbenzinga researchbenzinga prolog in get benzinga pro data apiseventsmarketfypremarketboostadvertisecontributedeutschespa olindiaitalianofran aissign inour services news...
 4. fusemachines fuse stock rises after modulaire ai partnership fusemachines nasdaq fuse benzingabenzingaespa aitalia fran aismy accountbenzinga edgebenzinga researchbenzinga prologinget benzinga pro data apiseventspremarketadvertisecontributeespa aitalia fran aisloginregisterbenzingapremium services financial news latestearningsguidancedividendsm abuybacksinterviewsmanagementofferingsiposinsider...
 5. view why ai can solve the password problem without personal responsibility languageenglish latest newsworldmarketspersonal financehealthcareindiaeconomypoliticstraveleducation careerssportsviewsautoentertainment technologystartups lifestyleretail real estateminisbranded contentceo awardsaccelerate your cloud journeythe unicorn makersaccelerating to connected futurefinancial services cloud...
 6. in data science professionals gained edge over peers through upskilling programmes emeritus india survey the financial express english english insurance insurance the financial express facebook twitter linkedin homeindia newsindustrymarket market indices nifty bse sensexhealthcaremoneyautoblockchainsmebrandwagonus stocksaudio switch to hindi edition homeelections budget market indices nifty...
 7. sam altman founded worldcoin crypto token crashes after his ouster from openai latestly cryptocurrency rates bitcoin btc ethereum eth tether usdt bnb bnb xrp xrp usdc usdc solana sol lido staked ether steth cardano ada dogecoin doge tron trx chainlink link avalanche avax polygon matic polkadot dot wrapped bitcoin wbtc dai dai litecoin ltc shiba inu shib toncoin ton bitcoin cash bch leo token...
 8. china tencent debuts large language ai model says open for enterprise use today at marketscreener edd imgaa qnpvwzu gjo ajehtorbvhvuzw rzjgtyywcg trcvp rvbafw ojhfddnqvakm hcqzkfu br tfbqoew vjiq advanced forgot password remember or with google apple email registration or with google apple english usa english uk english canada deutsch deutschland deutsch schweiz espa ol fran ais france fran ais...
 9. chatgpt ai platforms next big thing in learning education deborah quazzo of gsv ventures englishhindigujaratispecialssearch quotes news mutual fund navstrending stocksadani enterpris ine adanient adani power ine adanipower apple us aapl usadani ports ine adaniports microsoft us msft usquotesmutual fundscommoditiesfutures optionsnewscryptocurrencyforumnoticesvideosglossaryall hello loginhello...
10. mc explains what are artificial intelligence ethics englishhindigujaratispecialssearch quotes news mutual fund navstrending stocksadani enterpris ine adanient adani ports ine adaniports apple us aapl usadani power ine adanipower microsoft us msft usquotesmutual fundscommoditiesfutures optionsnewscryptocurrencyforumnoticesvideosglossaryall hello loginhello loginlog inor sign upmy accountmy...

============================================================
TOPIC 3
============================================================
 1. ubunye understands the true value ai brings to enhancing your dms about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps newsplugin live feed...
 2. orders surging and company financials growing stronger from marketing of ai security robots stock symbol aitx about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by...
 3. first book fully co written with chatgpt subsidiarity and virtues in the workplace now available as kindle about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by...
 4. consulting to invest in dataiku partnership to provide top notch ai and ml solutions for the life sciences industry about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country...
 5. from sci fi to reality ai is now shaping the health wellness industry about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps newsplugin live feed...
 6. miss date doctor dating coach london launch chatgpt dating advice virtual therapy unique relationship coaching services about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country...
 7. indiaspora inaugural ai summit beyond buzzwords can ai be force for good about about ein presswire how we are different better how it works testimonials company ethos contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps...
 8. global ai in cybersecurity market to exceed by driven by threat intelligence bfsi demand cloud adoption about about ein presswire how we are different better how it works testimonials company ethos ein presswire in the news ein presswire on substack ein presswire on trustpilot contact pricing distribution distribution overview media database major news sites tv radio stations international...

| Topic | Industry Label                              | Why                                                                                                                                                     |
| ----- | ------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------- |
| -1    | Cross-Industry AI News / Outliers                      | Contains broad AI coverage across many sectors with general keywords like *AI, technology, data*, indicating outlier articles not tied to one industry. |
| 0     | Enterprise Technology                       | Mentions companies like Google and Microsoft developing AI platforms, tools, and chips used in enterprise software.                                     |
| 1     | Consumer & Public Services                  | Articles show AI used in everyday services such as traffic enforcement, ordering systems, and community news contexts.                                  |
| 2     | Financial Services & Business               | Keywords like *market, stock, bank* and examples discussing company strategy and AI investment trends.                                                  |
| 3     | Corporate AI Announcements                  | Dominated by press releases and corporate announcements about AI partnerships, launches, and initiatives.                                               |
| 4     | Enterprise Software & Cybersecurity         | Articles focus on enterprise tools such as fraud prevention, analytics, and security solutions powered by AI.                                           |
| 5     | Healthcare & Life Sciences                  | Strong medical terms (*patients, cancer, healthcare*) and articles about diagnostics and medical AI applications.                                       |
| 6     | Financial Markets & Investing               | Focuses on AI stocks, share prices, and market commentary related to investing.                                                                         |
| 7     | Media, Journalism & Public Policy           | Coverage from public media discussing AI regulation, ethics, and societal impacts.                                                                      |
| 8     | Business Operations & Enterprise Automation | Articles describe AI used for customer service, banking operations, recruiting, and robotics.                                                           |
| 9     | Workforce & Compensation                    | Keywords like *salary, compensation, data scientist* show focus on labor market and AI-related jobs.                                                    |
| 10    | Cryptocurrency & Digital Assets             | Mentions tokens, crypto exchanges, and AI-related cryptocurrency price predictions.                                                                     |
| 11    | Publishing & Intellectual Property          | Articles discuss AI and copyright, publishing, and media licensing issues.                                                                              |
| 12    | Public AI Companies                         | Focuses on publicly traded AI companies and ETFs listed on exchanges like NASDAQ or NYSE.                                                               |
| 13    | Technology Industry News                    | Articles cover AI startups, business developments, and technology industry trends.                                                                      |
| 14    | Music & Entertainment                       | Includes AI-generated music, artists, and AI tools used in the entertainment industry.                                                                  |
| 15    | African Technology Development              | Articles discuss AI adoption and technology growth in African countries such as Nigeria and Ghana.                                                      |
| 16    | AI Market Commentary                        | Market analysis discussing AI-driven stock trends, valuations, and investment opportunities.                                                            |



Overall, the BERTopic model identifies several meaningful industry-related clusters such as healthcare AI, financial markets, cryptocurrency, and entertainment. However, some topics capture news sources or article formats rather than industries (e.g., press releases or local news outlets), even after filtering boilerplate out, which slightly reduces topic coherence. The presence of a large outlier cluster (-1) also indicates that many articles are broad AI news spanning multiple sectors. Despite these limitations, the model still provides a useful high-level view of how AI coverage is distributed across major industries.

### BERTopic Title
5 topics labeled from -1 to 3.

In [ ]:
# Load data
bertopic_title.head(2)

,url,date,title,text,bertopic_topic_title
0,https://blockworks.co/price/bad,2025-06-23,bad idea ai price bad market cap price today c...,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",0
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,this ai video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,0

In [ ]:
# Load info data
info_bertopic_title.head(5)

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1251,-1_bahamas_stew_native stew_bahamas ai,"[bahamas, stew, native stew, bahamas ai, stew ...",[native stew bahamas ai art photos videos baha...
1,0,131886,0_ai_news_chatgpt_new,"[ai, news, chatgpt, new, intelligence, openai,...",[from ai to ai why the magic box of artificial...

In [ ]:
# Representation words
for topic in sorted(info_bertopic_title["Topic"].unique()):
    rep = info_bertopic_title.loc[
        info_bertopic_title["Topic"] == topic, "Representation"
    ].iloc[0]

    print(f"\nTopic {topic}")
    print(rep)

Topic -1
['bahamas' 'stew' 'native stew' 'bahamas ai' 'stew bahamas' 'art photos'
 'photos videos' 'native' 'ai art' 'photos']

Topic 0
['ai' 'news' 'chatgpt' 'new' 'intelligence' 'openai' 'artificial'
 'artificial intelligence' 'google' 'com']

Topic 1
['salary' 'levels fyi' 'fyi' 'levels' 'scientist salary' 'data scientist'
 'scientist' 'data' 'salary levels' 'fyi data']

Topic 2
['le' 'ai' 'fa' 'ka' 'sa' 'na' 'ai le' 'metatrader' 'te' 'ho']

Topic 3
['philanthropic' 'new philanthropic' 'foundation' 'com' 'cellebrite'
 'donates' 'nonprofits' 'philanthropic funding' 'children' 'new']

In [ ]:
# Show example texts for each topic
for topic, group in bertopic_title.groupby("bertopic_topic_title"):
    print(f"\n{'='*60}")
    print(f"TOPIC {topic}")
    print(f"{'='*60}")

    for i, title in enumerate(group["title"].head(10), 1):
        snippet = shorten(str(title), width=400, placeholder="...")
        print(f"{i:>2}. {snippet}")

============================================================
TOPIC -1
============================================================
 1. magazine touted michael schumacher first interview in years it was actually ai alabama public radio
 2. tech firm baidu denies report that its ernie ai chatbot is linked to chinese military research wnct
 3. ai technology behind chatgpt was built in iowa data centers
 4. mlb testing hands free entry for fans utilizing facial authentication ai security klbk kamc everythinglubbock com
 5. how the tiny caribbean island of anguilla has turned the ai boom into digital gold mine whec com
 6. mark ai desktop app for mac windows pc linux webcatalog
 7. how is the ai boom transforming this caribbean island fortunes cryptopolitan
 8. best of mwc screens that roll chatgpt interactive glasses wate on your side
 9. norby ai desktop app for mac and pc webcatalog
10. lisk machine learning day trading volume tops lml american banking news

============================================================
TOPIC 0
============================================================
 1. bad idea ai price bad market cap price today chart history blockworks
 2. this ai video of gymnastics might be the freakiest ve seen yet boing boing
 3. if using ai feels like chore try this boing boing
 4. the road ahead how china ai foundation model is shaping the future of autonomous driving technology
 5. microsoft and nvidia to empower developers with windows ai studio
 6. google releases new chatbot bard as strong competitor to openai chatgpt
 7. zoom expands ai offering with ai companion and revenue accelerator
 8. pro ai thinking enhancing industrial environments with artificial intelligence
 9. best ai prompts for risk management
10. state ags warn ai companies clean up your child safeguards crooks and liars

============================================================
TOPIC 1
============================================================
 1. greenhouse software data scientist salary levels fyi
 2. proarch data scientist salary levels fyi
 3. eigen technologies data scientist salary levels fyi
 4. byjus future school data scientist salary levels fyi
 5. data scientist salary in lausanne switzerland
 6. kbr awarded analytic modeling and data science contracts worth over
 7. twitter senior data scientist salary in greater seattle area levels fyi
 8. decathlon data scientist salary levels fyi
 9. techstars data scientist salary levels fyi
10. kpmg data scientist salary levels fyi

============================================================
TOPIC 2
============================================================
 1. ma hea pehea ike ai ka annular solar eclipse
 2. waa maxay ai ugu awoodda badan adduunka
 3. ki sa ki gpt vle di
 4. mikor tekinthet az ai nek
 5. agropoli speciale sul premio delfino oro con le interviste ai premiati video
 6. google wuxuu bilaabay mashruuca mustaqbalka dijital ah si uu taageero cilmi baarista ai iyo xalka siyaasadda dadweynaha
 7. merevolusikan perniagaan dengan ai dan kontrak pintar masa depan biometrik dalam telekomunikasi
 8. te maramatanga ki nga mea interstellar na roto nga hihi ai ki nga kairangataiao
 9. ai le teine ropota tausaga le matua
10. fuafuaga le kalave theory fautua mai ai le paneta lona iva atonu le iai

============================================================
TOPIC 3
============================================================
 1. union pacific adds environmental sustainability as philanthropic priority
 2. ftx bankruptcy also endangers founder philanthropic gifts
 3. the rockefeller foundation announces million in new funding for data science platform global health to strengthen pathogen surveillance and response
 4. bridgid coulter cheadle forms community philanthropic voice
 5. how one powerful philanthropic competition is taking the fight against cancer by storm
 6. cognizant commits million in philanthropic support to expand stem education and access to tech careers
 7. uccil lauds mahima mishra entrepreneurial acumen philanthropic spirit confers coveted award
 8. new book re examines bill gates and melinda gates philanthropic work
 9. the billion dollar playbook daylight to launch first ever industry standard for philanthropic advisors
10. high school students challenge status quo in philanthropic competition to support blood cancer patients and families

| Topic | Industry Label                       | Why                                                                                                                                                                          |
| ----- | ------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| -1    | Cross-Industry AI News / Outliers              | Titles reference many unrelated areas (sports, tech, Caribbean economy, security systems), suggesting general AI news that doesn’t cluster into a single industry.           |
| 0     | Technology Industry & AI Development | Titles focus on AI tools, companies (OpenAI, Google, Microsoft), and AI product development such as chatbots and enterprise AI platforms.                                    |
| 1     | Workforce & Data Science Careers     | Nearly all titles mention *data scientist salaries* and compensation datasets (Levels.fyi), clearly indicating labor market information.                                     |
| 2     | Global / Multilingual AI News        | Titles appear in many different languages discussing AI concepts, suggesting the cluster formed around language patterns rather than a specific industry.                    |
| 3     | Philanthropy & Nonprofit Sector      | Keywords like *foundation, philanthropic funding, nonprofits,* and articles about charitable initiatives and funding programs indicate nonprofit and philanthropic activity. |

The BERTopic model using titles captures a few clear themes such as technology industry developments, workforce compensation, and philanthropy, but several topics are less coherent because titles contain limited context. One cluster primarily groups multilingual articles, indicating the model may be detecting language differences rather than industry themes. Additionally, the outlier topic (-1) contains general AI news spanning multiple sectors. Overall, title-based topic modeling provides a quick overview of themes but tends to produce broader or noisier clusters compared with full-text topic modeling.

### NMF Text
12 topics labeled from 0-11.

In [ ]:
# Load data
nmf_text.head(2)

,url,date,title,text,nmf_topic_text,nmf_topic_score_text,nmf_topic_words_text
0,https://blockworks.co/price/bad,2025-06-23,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",bad idea ai price bad market cap price today c...,6,0.012312,"share, share price, price, bank, bank share, i..."
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,This AI video of gymnastics might be the freak...,this ai video of gymnastics might be the freak...,10,0.018357,"apple, google, chatgpt, iphone, pro, best, sam..."

In [ ]:
# Load info data
info_nmf_text.head(12)

,topic,top_terms,top_term_scores
0,0,"cloud, generative, security, learning, custome...","0.8659, 0.8367, 0.8306, 0.8250, 0.8245, 0.8030..."
1,1,"newswires, presswire, ein presswire, ein, news...","2.0897, 1.1798, 1.1157, 1.0608, 0.7554, 0.6834..."

In [ ]:
# Representation words
for topic in sorted(info_nmf_text["topic"].unique()):
    top_terms = info_nmf_text.loc[
        info_nmf_text["topic"] == topic, "top_terms"
    ].iloc[0]

    print(f"\nTopic {topic}")
    print(top_terms)

Topic 0
cloud, generative, security, learning, customer, market, generative ai, management, digital, platform, solutions, models, agents, systems, enterprise

Topic 1
newswires, presswire, ein presswire, ein, newswires newswires, releases, south, distribution, north, guinea, dakota, carolina, virginia, republic, newswires industry

Topic 2
ment, overviewview, entertain ment, entertain, ment media, products, people culture, consumer, services, cision, general, policy public, send release, transportation, news releases

Topic 3
nasdaq, symbols, quotes, add, market, stocks, markets, symbol, watchlist, data currently, currently available, stock, add symbols, fool, edit

Topic 4
menafn, market, stocks, currencies, mena, research, indices, arab asia, europe arab, asia africa, stocks currencies, oil energy, arab, oil, press

Topic 5
salary, data scientist, compensation, scientist, salaries, total compensation, total, paying, fyi, pay, levels, levels fyi, time percentiles, percentiles, pay reporttop

Topic 6
share, share price, price, bank, bank share, india, mint, market, loan, rate, stock, stocks, pricetata, share pricetata, priceadani

Topic 7
ago, hours ago, hours, ago video, video, days ago, stories, bestreviews, file, days, nexstar, app, ap, local, mins ago

Topic 8
opens new, new window, opens, window, feed opens, cox media, cox, new tab, media group, tab, feed, click share, krmg, whio, window click

Topic 9
openai, said, chatgpt, altman, india, musk, tech, health, people, says, trump, live, microsoft, public, facebook

Topic 10
apple, google, chatgpt, iphone, pro, best, samsung, galaxy, microsoft, gemini, windows, features, users, reviews, gaming

Topic 11
march february, april march, february january, june april, july june, august july, november october, december november, september august, january december, october september, bahamas, february, august, april

In [ ]:
# Show example texts for each topic
for topic, group in nmf_text.groupby("nmf_topic_text"):
    print(f"\n{'='*60}")
    print(f"TOPIC {topic}")
    print(f"{'='*60}")

    for i, text in enumerate(group["text"].head(10), 1):
        snippet = shorten(str(text), width=400, placeholder="...")
        print(f"{i:>2}. {snippet}")

============================================================
TOPIC 0
============================================================
 1. the road ahead how china ai foundation model is shaping the future of autonomous driving technology ir ao contidoven de novembro de vida da cidadepresentando as novas tecnolox as poder da ia ainoticiaespazotecnolox asat litecienciaeuacontacto noticia cami por diante como modelo da fundaci ai de china est dar forma ao futuro da tecnolox de conduci aut noma by novembro cami por diante como modelo...
 2. zoom expands ai offering with ai companion and revenue accelerator skip to contentthu sep th citylifeunveiling new technologies and the power of ai ainewsspacetechnologysatellitescienceu contact technology zoom expands ai offering with ai companion and revenue accelerator byrobert andrew sep zoom video communications inc is embracing generative artificial intelligence ai by introducing two new...
 3. pro ai thinking enhancing industrial environments with artificial intelligence fri aug th citylife the power of ai models ai drones military news satellite telephony satellite internet space technology contact news pro ai thinking enhancing industrial environments with artificial intelligence bymampho brescia aug in the rapidly developing industrial landscape paradigm shift called pro ai...
 4. best ai prompts for risk managementproductsolutionslearnpricingenterprisecontact salessign uplog inmenuclose menuproductai built for youtasksdocsgoalswhiteboardsdashboardschatplatformrapidviews dbtemplatesintegrationsclickappshierarchyautomationssolutionssoftware developmentmarketingit and pmoengineeringdesignoperationsuse caseproject managementremote workcrmtypeenterprisestartupnon...
 5. principles to help federal agencies adopt ai ethically and securely fedtech magazine skip to main content become an insider today to receive premium content mobile topics agencies features tips tactics video capital events about insider feds in the field news reviews telehealth the byte voices main topics agencies features tips tactics video capital events about insider feds in the field news...
 6. cloudastructure artificial intelligence is revolutionizing cannabis surveillance get weed delivery shops rewards ht apparel cbd digital archive magazine subscription cannabis cup hightimes tv espa ol get weed delivery shops rewards ht apparel cbd digital archive magazine subscription cannabis cup hightimes tv espa ol featured categories news view posts guides view posts grow view posts events...
 7. jukin licensing unveils advanced ai integration lbbonlineedition global usa uk aunz canada ireland france germany asia europe latam mea edition internationallanguage english homenewscreative libraryimmortal awardsmember companiespeoplejobshow lbb worksplans pricingeditorial toolkitnewsnewscreative libraryimmortal awardsmember companiespeoplejobslogin or registerhires wins in association withlbb...
 8. the key to responsible ai development archive directory biztech tv videos tv year in review headlines budget archive trade exchange rate stock exchange gse homenewssportsbusinessentertainmentghanaweb tvafricacountrywall menu the key to responsible ai development artificial intelligence tue apr source aviationghana com in recent months the development of artificial intelligence has accelerated...
 9. will generative ai improve customers experiences interacting with retailers retailwire skip to main content sign up for retailwire newsletters don miss out for discussions front page discussions retail news resources braintrust marketing about front page discussions retail news resources braintrust marketing about for for discussionsnewsletter front page discussions retail news resources...
10. aaron levie leads box into its third era focused on workflow automation and ai techcodex mobile gadgets internet virtual reality artificial intelligence computing reviews the best how to mobile gadgets internet virtual reality artificial intelligence computing reviews the best how to artificial intelligence aaron levie leads box into its third era focused on workflow automation and ai aaron...

============================================================
TOPIC 1
============================================================
 1. ubunye understands the true value ai brings to enhancing your dms about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps newsplugin live feed...
 2. orders surging and company financials growing stronger from marketing of ai security robots stock symbol aitx about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by...
 3. first book fully co written with chatgpt subsidiarity and virtues in the workplace now available as kindle about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by...
 4. consulting to invest in dataiku partnership to provide top notch ai and ml solutions for the life sciences industry about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country...
 5. from sci fi to reality ai is now shaping the health wellness industry about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps newsplugin live feed...
 6. miss date doctor dating coach london launch chatgpt dating advice virtual therapy unique relationship coaching services about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country...
 7. indiaspora inaugural ai summit beyond buzzwords can ai be force for good about about ein presswire how we are different better how it works testimonials company ethos contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps...
 8. global ai in cybersecurity market to exceed by driven by threat intelligence bfsi demand cloud adoption about about ein presswire how we are different better how it works testimonials company ethos ein presswire in the news ein presswire on substack ein presswire on trustpilot contact pricing distribution distribution overview media database major news sites tv radio stations international...
 9. businesses seek to balance ai innovation and ethics according to deloitte techrepublic top products ai developer payroll security project management academy toggle techrepublic mobile resources techrepublic premium techrepublic academy newsletters resource library sponsored go premium popular topics top products ai developer payroll security project management academy project management...
10. digital wave technology exhibits maestro ai at nrf about about ein presswire how we are different better how it works testimonials contact ein presswire in the news pricing distribution distribution overview media database major news sites tv radio stations international newswires newswires by industry newswires by country newswires by state mobile apps newsplugin live feed sample distribution...

============================================================
TOPIC 2
============================================================
 1. revieve and debenhams redefine uk beauty standards with groundbreaking ai and ar powered consultation experiences resources journalists data privacy send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in focus browse news releases...
 2. palo alto networks forecasts predictions on securing the new ai economy for accessibility statement skip navigation resources investor relations journalists agencies client send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in...
 3. sanas raises for breakthrough ai technology for real time accent translation resources journalists data privacy send release news products overview distribution by pr newswire cision communications cloud cision ir sponsored placement all products contact general inquiries request demo editorial bureaus partnerships media inquiries worldwide offices when typing in this field list of results will...
 4. annum capital and turoid unlocking ai for asia family offices accessibility statement skip navigation prnewswire com resources client send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please use advanced to all press releases news in focus browse news releases all news...
 5. idology to showcase complete ecosystem of fraud prevention in money usa talk why ai needs humans resources journalists data privacy send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in focus browse news releases all news releases...
 6. kipi ai delivers marketing mix modeling and analytics app on snowflake ai data cloud resources journalists data privacy send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in focus browse news releases all news releases all public...
 7. government of canada finalizes investment to support canadian born ai leader cohere accessibility statement skip navigation resources journalists webcasts data privacy fran ais my cnw register client online member centre next gen communications cloud cision communications cloud send release news products contact when typing in this field list of results will appear and be automatically updated...
 8. meizu to debut ai full ecosystem products at mwc accessibility statement skip navigation resources journalists client send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in focus browse news releases all public company news all...
 9. sony semiconductor solutions and raspberry pi launch the raspberry pi ai camera resources journalists data privacy send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in focus browse news releases all public company news all...
10. synechron launches synechron nexus plus ai accelerators program to propel corporate growth resources journalists data privacy send release news products contact when typing in this field list of results will appear and be automatically updated as you type searching for your content no results found please change your terms and try again news in focus browse news releases all public company news...

============================================================
TOPIC 3
============================================================
 1. artificial intelligence ai stocks to buy and hold for decades news life shopping yahoo plus to view your watchlists my portfolio markets yf chartbook calendars trending tickers stocks most actives stocks gainers stocks losers top etfs futures indices currencies top mutual funds options highest open interest options highest implied volatility us treasury bonds rates currency converter news...
 2. equinix stock market leader positioned for ai growth but is it buy nasdaq eqix seeking alphaskip to contenthome page seeking alpha power to investorscreate free accountabout premiumfree newslettershomestock analysisstock ideasmarket outlookinvesting strategylong ideasipo analysiseditor pickscryptocurrencymarket newstop market newsnotable callson the moveearnings newsenergy stock newstech stock...
 3. fusemachines fuse stock rises after modulaire ai partnership fusemachines nasdaq fuse benzingabenzingaespa aitalia fran aismy accountbenzinga edgebenzinga researchbenzinga prologinget benzinga pro data apiseventspremarketadvertisecontributeespa aitalia fran aisloginregisterbenzingapremium services financial news latestearningsguidancedividendsm abuybacksinterviewsmanagementofferingsiposinsider...
 4. best ai stocks to buy in september to watch nasdaq skip to main content nasdaq weekly macro market activity market activity stocks options etfs mutual funds indexes commodities cryptocurrency currencies futures fixed income global markets market regulation regulation european regulation quick links real time quotes after hours quotes pre market quotes nasdaq symbol screener online brokers...
 5. the new browser wars alphabet distribution dominance is an ai moat nasdaq skip to main content nasdaq weekly macro scorecard market activity market activity stocks options etfs mutual funds indexes cryptocurrency currencies fixed income trading market services north american markets nasdaq index nasdaq index options market data european markets shares indexes fixed income options futures etps...
 6. this ai stock is running circles around upstart and wall street sees upside nasdaq skip to main content nasdaq market recap market activity market activity stocks options etfs mutual funds indexes commodities cryptocurrency currencies futures fixed income global markets quick links real time quotes after hours quotes pre market quotes nasdaq symbol screener online brokers glossary sustainable...
 7. amplify ai powered equity etf nysearca aieq trading higher here what happened markets daily skip to main content account about contact stocks technology health lifestyle politics account about contact stocks technology health lifestyle politics amplify ai powered equity etf nysearca aieq trading higher here what happened posted by tristan rich on nov th share on twitter share on facebook share...
 8. short interest in multisensor ai holdings inc nasdaq msai rises by community financial news skip to main content headlines about us account news technology education headlines about us account news technology education short interest in multisensor ai holdings inc nasdaq msai rises by posted by eileen french on jul th share on twitter share on facebook share on linkedin share on stocktwits...
 9. no brainer artificial intelligence ai stocks to buy right now nasdaq skip to main content nasdaq weekly macro scorecard market activity market activity stocks options etfs mutual funds indexes cryptocurrency currencies fixed income trading market services north american markets nasdaq index nasdaq index options market data european markets shares indexes fixed income options futures etps...
10. should you buy ses ai corporation ses after golden cross nasdaq skip to main content nasdaq weekly macro scorecard market activity market activity stocks options etfs mutual funds indexes cryptocurrency currencies fixed income trading market services north american markets nasdaq index nasdaq index options market data european markets shares indexes fixed income options futures etps warrants...

============================================================
TOPIC 4
============================================================
 1. dutch ai data center reduces cooling costs and embraces green technology with waste heat power generation system remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices...
 2. immunoassay market to grow by usd billion driven by early diagnosis advances with ai impacting market trends technavio remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena...
 3. europe wearable ai market report robust growth projected with healthcare and industrial applications leading the charge tuesday january gmt remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market...
 4. ai cctvs deployed in peru lima district for public safety tuesday january gmt remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices qutoes charts end of day stocks...
 5. scribblevet welcomes dr jeff werber as chief veterinary advisor announces enhancements to ai scribe solution remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices...
 6. trump administration plans national ai rules to counter state laws tuesday january gmt remember me new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices qutoes charts end of day stocks currencies currency...
 7. classic collision implements ai to automate hr and compliance management across hundreds of locations in states remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices...
 8. the rise of generative ai revolutionizing content creation and the role of ai detectors robotics automation news remember me forgot username or password new here create an account news news by industry news by region american europe arab asia africa rss press distribution press releases submit your articles press releases reports pricing market data equities market global indices mena indices...

| Topic | Industry Label                               | Why                                                                                                                                                                   |
| ----- | -------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 0     | Enterprise Software & Digital Transformation | Terms like *cloud, generative ai, platform, enterprise, customer,* and examples on workflow automation and agency adoption point to enterprise AI tools and software. |
| 1     | Corporate Announcements & Press Releases     | Dominated by *EIN Presswire/newswires* terms, so this cluster reflects press-release distribution more than a single industry.                                        |
| 2     | Enterprise Technology & Business Solutions   | Includes product and service language, with examples on fraud prevention, analytics, AI devices, and corporate growth tools.                                          |
| 3     | Financial Markets & AI Stocks                | Keywords like *nasdaq, quotes, symbol, stocks, watchlist* clearly indicate stock-market and investing content.                                                        |
| 4     | Global Market News & Industry Reports        | Terms like *menafn, market, currencies, indices* and examples spanning AI market reports, regulation, and sector updates suggest broad market-news coverage.          |
| 5     | Workforce & Data Science Careers             | Strong salary-related terms such as *data scientist, compensation, pay, levels fyi* make this a jobs and compensation cluster.                                        |
| 6     | Finance, Equities & Crypto Assets            | Combines *share price, bank, market, stock* with examples on company shares and AI-linked crypto/token pricing.                                                       |
| 7     | General News / Local News AI Coverage        | Terms like *hours ago, stories, file, local* and examples from local outlets suggest news-format clustering rather than one industry.                                 |
| 8     | Local Media & News Site Boilerplate          | Phrases like *opens new window, cox media, click share* are mostly website/navigation text, so this is source-format noise.                                           |
| 9     | General AI Industry News                     | Contains broad terms like *OpenAI, ChatGPT, Musk, Microsoft, public* and mixed examples across policy, entertainment, and tech.                                       |
| 10    | Consumer Technology & Devices                | Keywords such as *Apple, Google, iPhone, Samsung, Windows, features, reviews* point to consumer tech products and platforms.                                          |
| 11    | Date / Template Boilerplate                  | Month sequences and weak topical words show this is mostly formatting or scraping noise, not a real industry theme.                                                   |

Overall, the NMF text model finds several useful themes, especially enterprise AI, financial markets, consumer tech, and workforce/salary content. At the same time, a few topics are driven by source boilerplate or page-template text rather than real semantic themes, especially Topics 1, 8, and 11, and Topic 7 is fairly broad. So the model is moderately strong for high-level industry grouping, but it would likely improve with more aggressive cleaning of navigation, press-release, and date-template text.

### NMF Title
16 topics labeled from 0-15.

In [ ]:
# Load data
nmf_title.head(2)

,url,date,title,text,nmf_topic_title,nmf_topic_score_title,nmf_topic_words_title
0,https://blockworks.co/price/bad,2025-06-23,bad idea ai price bad market cap price today c...,"Bad Idea AI Price (BAD), Market Cap, Price Tod...",14,0.051832,"price, mexc, price prediction, prediction, for..."
1,https://boingboing.net/2024/07/01/this-ai-vide...,2024-07-01,this ai video of gymnastics might be the freak...,This AI video of gymnastics might be the freak...,12,0.002563,"art, ai art, bahamas, videos, photos, photos v..."

In [ ]:
# Load info data
info_nmf_title.head(16)

,topic,top_terms,top_term_scores
0,0,"intelligence, artificial, artificial intellige...","3.5159, 3.4948, 3.4834, 0.5154, 0.2551, 0.1700..."
1,1,"salary, data scientist, scientist, scientist s...","2.0412, 1.9863, 1.9701, 1.9445, 1.8507, 1.8506..."

In [ ]:
# Representation words
for topic in sorted(info_nmf_title["topic"].unique()):
    top_terms = info_nmf_title.loc[
        info_nmf_title["topic"] == topic, "top_terms"
    ].iloc[0]

    print(f"\nTopic {topic}")
    print(top_terms)

Topic 0
intelligence, artificial, artificial intelligence, intelligence ai, market, com, using artificial, global, use artificial, future, pledge times, pledge, intelligence help, technology, industry

Topic 1
salary, data scientist, scientist, scientist salary, levels fyi, fyi, levels, salary levels, data, salary united, ca, manager salary, area, area levels, united

Topic 2
new, new ai, launches, technology, tool, model, unveils, launches new, ai model, ai tool, new technology, features, tools, announces, unveils new

Topic 3
generative, generative ai, launches, market, platform, software, cloud, tools, capabilities, com, new generative, ai capabilities, ai tools, enterprise, announces

Topic 4
learning, machine, machine learning, ai machine, using, safetylit, using machine, market, intelligence machine, based, models, learning models, using ai, webcatalog, learning ai

Topic 5
openai, altman, sam, sam altman, ceo, microsoft, openai ceo, ceo sam, gpt, says, board, openai sam, sora, billion, maker

Topic 6
chatgpt, use, use chatgpt, using, like, users, com, using chatgpt, openai, gadgets, geeky gadgets, geeky, chatgpt ai, app, openai chatgpt

Topic 7
news, tech, standard, tech news, news standard, technology, latest, latest news, breaking, mexc news, breaking latest, technology news, telecom, et, company

Topic 8
nasdaq, stock, stocks, nvidia, buy, ai stock, ai stocks, intelligence ai, stocks buy, market, ai nasdaq, soundhound, soundhound ai, chip, wall

Topic 9
google, gemini, google ai, bard, chatbot, gemini ai, ai chatbot, google bard, google gemini, cloud, microsoft, google cloud, exbulletin, features, model

Topic 10
times, india, economic, economic times, times india, hindustan, hindustan times, pledge, pledge times, global, news times, india ai, says, khaleej times, khaleej

Topic 11
data, science, data science, ai data, center, manager, science manager, manager salary, data center, online, centers, data centers, launches, data ai, platform

Topic 12
art, ai art, bahamas, videos, photos, photos videos, art photos, bahamas ai, stew bahamas, stew, native stew, native, wallpaper, pc, pc wallpaper

Topic 13
product, hunt, product hunt, ai product, powered, agent, assistant, ai powered, gpt, using, ai agent, create, using ai, ai assistant, agents

Topic 14
price, mexc, price prediction, prediction, forecasts mexc, forecasts, mexc exchange, exchange, price forecasts, prediction price, crypto, market, chart, price chart, trends

Topic 15
musk, elon, elon musk, grok, chatbot, ai chatbot, grok ai, xai, musk ai, says, musk says, tesla, musk grok, company, musk xai

In [ ]:
# Show example texts for each topic
for topic, group in nmf_title.groupby("nmf_topic_title"):
    print(f"\n{'='*60}")
    print(f"TOPIC {topic}")
    print(f"{'='*60}")

    for i, title in enumerate(group["title"].head(10), 1):
        snippet = shorten(str(title), width=400, placeholder="...")
        print(f"{i:>2}. {snippet}")

============================================================
TOPIC 0
============================================================
 1. pro ai thinking enhancing industrial environments with artificial intelligence
 2. cloudastructure artificial intelligence is revolutionizing cannabis surveillance
 3. copa libertadores artificial intelligence gives its winner of the duel between millonarios vs flamengo pledge times
 4. tiger king joe exotic releases artificial intelligence porn clone
 5. games with artificial intelligence genius ai tienstiens
 6. virtus artificial intelligence amp technology opportunities fund discloses sources of distribution section notice
 7. driven by artificial intelligence micron sees robust chip demand
 8. sanctions ordered for lawyers who relied on chatgpt artificial intelligence to prepare court brief courthouse news service
 9. uk plans ai summit to assert global leadership in artificial intelligence cryptopolitan
10. global ai in cybersecurity market to exceed by driven by threat intelligence bfsi demand cloud adoption

============================================================
TOPIC 1
============================================================
 1. young scientist entrants use ai to predict cryptocurrency values
 2. greenhouse software data scientist salary levels fyi
 3. proarch data scientist salary levels fyi
 4. fed state it leaders share tips in data scientist recruiting race meritalk
 5. eigen technologies data scientist salary levels fyi
 6. byjus future school data scientist salary levels fyi
 7. data scientist salary in lausanne switzerland
 8. twitter senior data scientist salary in greater seattle area levels fyi
 9. data scientist jobbusters ab datajobb stockholm
10. decathlon data scientist salary levels fyi

============================================================
TOPIC 2
============================================================
 1. qualcomm announces new ai chips in data center push shares surge
 2. meta releases seamlessm translation ai for text and speech
 3. jukin licensing unveils advanced ai integration lbbonline
 4. ai cctvs deployed in peru lima district for public safety
 5. aaron levie leads box into its third era focused on workflow automation and ai techcodex
 6. magazine touted michael schumacher first interview in years it was actually ai alabama public radio
 7. symbolic language empowers ai applications opening new frontiers
 8. michael best creates new officer role for ai implementation law pulse
 9. global ai technology trend tvbs exclusive broadcast and interview with jensen huang reaches new heights malay
10. new ai tool set to bust fraudsters and tackle money laundering

============================================================
TOPIC 3
============================================================
 1. the key to responsible ai development
 2. will generative ai improve customers experiences interacting with retailers retailwire
 3. glia completes th year of growth fueled by strong adoption of its digital customer service platform and ai automation solutions
 4. state of ai in the enterprise fifth edition uncovers four key actions to maximize ai value finanzen at
 5. ust to train over employees in generative ai technologies
 6. do it right with ai ally creators experiment with generative ai in marketing test case
 7. omdia enterprise ai has reached critical mass
 8. businesses seek to balance ai innovation and ethics according to deloitte
 9. companies rely on multiple methods to secure generative ai tools
10. breaking new ground the role of generative ai in agritech express computer

============================================================
TOPIC 4
============================================================
 1. create machine safety videos boost training with ai heygen
 2. new ai incubation hub to work on critical tech for army machine learning robotics big data in focus
 3. harvard ai based on president claudine gay taken down over allegations of racist stereotyping
 4. ma hea pehea ike ai ka annular solar eclipse
 5. landing ai adds new edge capabilities to landinglens to bring deep learning to the factory floor
 6. we recall drugs with adverse effects so why not recall ai algorithms with racial bias newsbreak
 7. safetylit application of machine learning models and shap to examine crashes involving young drivers in new jersey
 8. australian facebook and instagram posts are feeding meta ai machine techradar
 9. researchers who helped lay the groundwork for ai win nobel prize in physics wlrn
10. top ai writing assistants bhutan webcatalog

============================================================
TOPIC 5
============================================================
 1. openai goes in of suckers in hollywood exbulletin
 2. sam altman founded worldcoin crypto token crashes after his ouster from openai latestly
 3. foundry for ai by rackspace launches two step flight plan for copilot for microsoft forextv
 4. openai integrates ai into humanoid robots new era of technological evolution
 5. openai project strawberry said to be building ai that reasons and does deep research
 6. former openai cto mira murati raises billion for six month old ai startup with no disclosed products
 7. microsoft and contracts to present navigating the future ai in contracting to taiwan legal officers association
 8. chatgpt creator sam altman testifies in congress about ai risks los angeles times
 9. sam altman openai may launch chatgpt based social network report
10. deep ai appoints tim keliher as chief revenue officer

============================================================
TOPIC 6
============================================================
 1. if using ai feels like chore try this boing boing
 2. chatgpt can chatbot preach good sermon hundreds attend church service generated by chatgpt to find out the economic times
 3. edtech chegg rallies as strong quarter eases fears about chatgpt impact
 4. chatgpt maker openai says it is doubling down on preventing ai from going rogue businessworld online
 5. mom says she uses chatgpt to co parent and plan meals bedtime and gifts now she public enemy
 6. first book fully co written with chatgpt subsidiarity and virtues in the workplace now available as kindle
 7. miss date doctor dating coach london launch chatgpt dating advice virtual therapy unique relationship coaching services
 8. how you can use ai to help market your products
 9. can chatbot preach good sermon hundreds attend church service generated by chatgpt to find out ksnf kode fourstateshomepage com
10. the best chatgpt apps for iphone slashgear

============================================================
TOPIC 7
============================================================
 1. the road ahead how china ai foundation model is shaping the future of autonomous driving technology
 2. state ags warn ai companies clean up your child safeguards crooks and liars
 3. bullfrog ai holdings inc bfrg revenue clocked in at million up ytd what next the dbt news
 4. principles to help federal agencies adopt ai ethically and securely fedtech magazine
 5. hasbro may be eyeing ai for dungeons dragons
 6. taiwan puts companies behind china ai ambitions on export control list news channel
 7. late night with the devil sparks ai debate in indie cinema the week
 8. ap source flyers trade captain claude giroux to panthers wsvn news miami news fort lauderdale
 9. chat gpt news latest news and headlines from australia and the
10. nvidia ceo suggests malaysia could be ai manufacturing hub as southeast asia expands data centers action news jax

============================================================
TOPIC 8
============================================================
 1. microsoft and nvidia to empower developers with windows ai studio
 2. best ai prompts for risk management
 3. artificial intelligence ai stocks to buy and hold for decades
 4. nvidia and ubisoft are working on neo npcs ai characters that can react to the actions of players and the environment
 5. europe wearable ai market report robust growth projected with healthcare and industrial applications leading the charge
 6. equinix stock market leader positioned for ai growth but is it buy nasdaq eqix seeking alpha
 7. mark zuckerberg lays down how meta will make money from its multi billion dollar ai bet meta platforms nasdaq meta benzinga
 8. fusemachines fuse stock rises after modulaire ai partnership fusemachines nasdaq fuse benzinga
 9. correction in overly optimistic asset valuations will happen if ai boom fails to deliver the anticipated productivity gains survey newsalert
10. orders surging and company financials growing stronger from marketing of ai security robots stock symbol aitx

============================================================
TOPIC 9
============================================================
 1. google releases new chatbot bard as strong competitor to openai chatgpt
 2. zoom expands ai offering with ai companion and revenue accelerator
 3. microsoft brings dall ai image generation to bing and edge
 4. imagen network image to integrate advanced llama based ai for multimodal personalization it net
 5. union pacific adds environmental sustainability as philanthropic priority
 6. anthropic forges partnership with google cloud to help deliver reliable and responsible ai
 7. ubunye understands the true value ai brings to enhancing your dms
 8. rescale inc slurm rescale connector brings fully managed serverless cloud with secure on demand access to common hpc ai applications
 9. google gemma open source ai optimized to run on nvidia gpus geeky gadgets
10. samsung develops ultra large ai system to compete with language models impact lab

============================================================
TOPIC 10
============================================================
 1. insmind launches ai agent for smarter flexible visual creation laotian times
 2. these smart glasses have camera and integrated chatgpt they are cheaper than you think pledge times
 3. mumbaihacks pioneering ai innovation in india technology
 4. trump ai ambition china deepseek overshadow ai summit in paris
 5. china tencent debuts large language ai model says open for enterprise use today at marketscreener
 6. wanted an ai job that mostly doesn exist yet orlando sentinel
 7. us china ai rivalry intensifies as deepseek enters the fray by shuaib agaka
 8. wanted an ai job that mostly doesn exist yet santa cruz sentinel
 9. how to improve ai outputs using advanced prompt techniques thoughtworks india
10. meta faces italian competition investigation over whatsapp ai chatbot the economic times

============================================================
TOPIC 11
============================================================
 1. dutch ai data center reduces cooling costs and embraces green technology with waste heat power generation system
 2. why is private ai the next frontier for enterprises
 3. trinity life sciences appoints jonathan jenkins from mckinsey quantumblack to head up its digital ai initiatives biospace
 4. consulting to invest in dataiku partnership to provide top notch ai and ml solutions for the life sciences industry
 5. in data science professionals gained edge over peers through upskilling programmes emeritus india survey the financial express
 6. announcing ibm real time ai for transaction processing at scale and industry first quantum safe system
 7. publisher monetization company arcspan technologies adds key roles in adtech sales and data science hires kelly merton and artemio rimando
 8. blend announces immediate plans to hire data engineers globally
 9. harvard review research reveals how ai is making the recruiting process effective and positively impacting success
10. sanctuary ai acquires key ip assets related to touch and grasping vital to building truly general purpose robots

============================================================
TOPIC 12
============================================================
 1. this ai video of gymnastics might be the freakiest ve seen yet boing boing
 2. forestry report video maker create ai videos easily heygen
 3. creative theft arts and screen bodies respond to ai proposals in pc report
 4. onboarding guide video maker build ai onboarding guides heygen
 5. biden white house alarmed over sexually explicit taylor swift ai photos
 6. trump lashes out at ai photos that make him look fat immediately after ny fraud ruling inquisitr
 7. pen strokes or pixels the great debate around ai in art
 8. popular ai art tool dall gets big upgrade from chatgpt creator openai techradar
 9. loab the creepy ai art generated woman explained cnet
10. sunglasses summer accessories reflection ai premium photo rawpixel

============================================================
TOPIC 13
============================================================
 1. the dell validated solution for conversational ai itzikr
 2. view why ai can solve the password problem without personal responsibility
 3. the timekettle ai interpreter earbuds debut at ifa with bone voiceprint sensor capture and llm powered context aware translation to distinguish phonetically similar phrases
 4. exclusive getty images enables custom ai creations pcmag
 5. revieve and debenhams redefine uk beauty standards with groundbreaking ai and ar powered consultation experiences
 6. helix your collaborative ai coding agent product hunt
 7. collections bureau of america ltd adopts skit ai voice ai solution to enhance account penetration and customer experience
 8. spotify collaborates with record labels to build ai tools that put artists first
 9. who will win the kentucky derby crowd sourced picks from experts enthusiasts ai chat bots the athletic
10. gohighlevel ai agent feature released delivering scalable automation for agencies and marketers

============================================================
TOPIC 14
============================================================
 1. bad idea ai price bad market cap price today chart history blockworks
 2. immunoassay market to grow by usd billion driven by early diagnosis advances with ai impacting market trends technavio
 3. how to buy bicity ai projects bicity guide mexc
 4. innovia ai invaai price prediction price forecasts mexc exchange
 5. glitch gremlin ai gremlinai price chart news crypto prices trends on mexc
 6. origent ai ori price prediction price forecasts mexc exchange
 7. dora insights where is ai really driving developer productivity gitlab
 8. vymo rise of ai report highlights the the role of ai in transforming insurance distribution in
 9. acid ai acid price prediction price forecasts mexc exchange
10. bad idea ai bad price prediction price forecasts mexc exchange

============================================================
TOPIC 15
============================================================
 1. xai elon musk presents new artificial intelligence technology the goa spotlight
 2. elon musk sharply criticises apple google ai deal calls it unreasonable concentration of power of tech giants latestly
 3. judge approves billion copyright settlement between ai company anthropic and authors
 4. tech firm baidu denies report that its ernie ai chatbot is linked to chinese military research wnct
 5. openai legal battle with elon musk reveals internal turmoil over avoiding ai dictatorship abc news
 6. elon musk mark zuckerberg visit us congress to discuss ai technology gulf news
 7. albanian pm says ai minister pregnant with ai children to assist party mps
 8. optum ai chatbot was left publicly accessible
 9. musk vs altman openai trial testimony will blow your mind says musk microsoft nasdaq msft benzinga
10. the apprentice claude littner says its not my call as replacement returns to bbc show chronicle live

| Topic | Industry Label                      | Why                                                                                                                                                                |
| ----- | ----------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| 0     | General AI Industry News            | Broad terms like *artificial intelligence, market, industry,* and mixed examples across chips, law, sports, and cybersecurity indicate cross-industry AI coverage. |
| 1     | Workforce & Data Science Careers    | Dominated by *data scientist, salary, levels fyi,* and examples about recruiting, jobs, and compensation.                                                          |
| 2     | AI Product Launches & Applications  | Terms like *launches, tool, model, unveils* and examples on chips, fraud tools, public safety, and workflow automation point to new AI product rollouts.           |
| 3     | Enterprise Generative AI            | Strong *generative ai, platform, software, enterprise, capabilities* language and examples on adoption, marketing, and enterprise value.                           |
| 4     | Applied AI & Machine Learning       | Built around *machine learning, models, using ai* with examples spanning safety, robotics, factories, bias, and writing tools.                                     |
| 5     | OpenAI & AI Leadership News         | Centered on *OpenAI, Sam Altman, CEO, Microsoft* and examples about leadership, funding, strategy, and congressional testimony.                                    |
| 6     | ChatGPT Consumer Use Cases          | Focuses on *ChatGPT, use, users, app* and examples involving sermons, parenting, dating advice, marketing, and mobile apps.                                        |
| 7     | General Tech News & Policy          | Mixed *news, tech, latest, company* terms and examples on regulation, exports, entertainment, sports, and public policy make this a broad news cluster.            |
| 8     | AI Stocks & Semiconductors          | Terms like *nasdaq, stock, ai stocks, nvidia, soundhound, chip* clearly point to investing and public-market AI coverage.                                          |
| 9     | Google AI & Cloud Platforms         | Centered on *Google, Gemini, Bard, chatbot, Google Cloud* with examples on Google products, partnerships, and model launches.                                      |
| 10    | India & Global AI News              | Terms like *India, Economic Times, Hindustan Times* and examples tied to India, China, jobs, and policy suggest a regional news cluster.                           |
| 11    | Data Infrastructure & Enterprise AI | Terms such as *data science, data center, platform* and examples on enterprise hiring, transaction systems, robots, and AI deployments.                            |
| 12    | AI Art & Visual Media               | Clear keywords like *ai art, photos, videos* and examples on image generation, celebrity AI images, and debate around AI art.                                      |
| 13    | AI Products, Agents & Assistants    | Terms like *product hunt, ai powered, agent, assistant* and examples on coding agents, translation earbuds, voice AI, and marketing automation.                    |
| 14    | AI Crypto & Market Forecasts        | Dominated by *price, mexc, price prediction, forecasts, crypto* with examples on token prices and AI-related crypto assets.                                        |
| 15    | Elon Musk, xAI & AI Controversy     | Built around *musk, elon musk, grok, xai* and examples about lawsuits, politics, rivalries, and public disputes involving Musk and AI.                             |

Overall, this NMF title model produces several interpretable themes such as AI product launches, ChatGPT usage, AI stocks, Google AI, and AI art. However, compared with the BERTopic results, many topics are less clearly tied to specific industries and instead reflect technology trends, companies, or news narratives. For example, clusters around OpenAI leadership, Elon Musk, and ChatGPT usage capture prominent actors and applications rather than distinct industry sectors. As a result, while the model captures meaningful themes in AI coverage, it provides weaker industry segmentation and more general topical groupings.